part of 'app_strings.dart';

const Map<String, Map<String, String>> _autoAwayFeatureTranslations = {
  "vi": {
    "chooseOnMap": "Chọn trên bản đồ",
    "participantsTitle": "Thành viên xác định chế độ",
    "statusParticipantsCount": "Số thành viên dùng để xác định mở Tự động bảo vệ",
    "participantsDescription": "Chỉ những thành viên được chọn mới được dùng để quyết định khi nào tự động Bảo vệ bật hoặc trở về Bình thường.",
    "selectAtLeastOneParticipant": "Hãy chọn ít nhất một thành viên.",
    "mapTitle": "Chọn vị trí nhà",
    "mapHint": "Chạm vào bản đồ để di chuyển ghim vị trí nhà.",
    "confirmMapLocation": "Xác nhận vị trí nhà",
    "enabledForSelectedParticipants": "Đã bật tự động Bảo vệ theo những thành viên được chọn.",
    "selectedMembersPermissionHint": "Những thành viên được chọn cần cấp quyền vị trí Luôn cho phép để trạng thái rời/đến nhà hoạt động khi ứng dụng chạy nền.",
  },
  "en": {
    "chooseOnMap": "Choose on map",
    "participantsTitle": "People used for Auto Protection",
    "statusParticipantsCount": "People used for Auto Protection",
    "participantsDescription": "Only selected people are used to decide when Auto Protection turns on or returns to Normal.",
    "selectAtLeastOneParticipant": "Select at least one person.",
    "mapTitle": "Choose home location",
    "mapHint": "Tap the map to move the home marker.",
    "confirmMapLocation": "Confirm home location",
    "enabledForSelectedParticipants": "Auto Protection was enabled for the selected people.",
    "selectedMembersPermissionHint": "Selected people need Always location permission so arrivals and departures work in the background.",
  },
  "zh": {
    "chooseOnMap": "在地图上选择",
    "participantsTitle": "用于自动防护的成员",
    "statusParticipantsCount": "用于自动防护的成员",
    "participantsDescription": "只有选中的成员用于决定何时开启自动防护或恢复正常模式。",
    "selectAtLeastOneParticipant": "请至少选择一名成员。",
    "mapTitle": "选择家庭位置",
    "mapHint": "点击地图可移动家庭位置标记。",
    "confirmMapLocation": "确认家庭位置",
    "enabledForSelectedParticipants": "已为所选成员启用自动防护。",
    "selectedMembersPermissionHint": "所选成员需要授予“始终允许”位置权限，才能在应用后台运行时识别离家和回家。",
  },
  "ko": {
    "chooseOnMap": "지도에서 선택",
    "participantsTitle": "자동 보호 판단 구성원",
    "statusParticipantsCount": "자동 보호 판단 구성원",
    "participantsDescription": "선택한 구성원만 자동 보호를 켜거나 일반 모드로 돌아갈 시점을 판단하는 데 사용됩니다.",
    "selectAtLeastOneParticipant": "구성원을 한 명 이상 선택하세요.",
    "mapTitle": "집 위치 선택",
    "mapHint": "지도를 탭하여 집 위치 핀을 이동하세요.",
    "confirmMapLocation": "집 위치 확인",
    "enabledForSelectedParticipants": "선택한 구성원을 기준으로 자동 보호를 켰습니다.",
    "selectedMembersPermissionHint": "선택한 구성원은 앱이 백그라운드에 있을 때 출발과 도착을 감지할 수 있도록 위치 권한을 항상 허용해야 합니다.",
  },
  "ja": {
    "chooseOnMap": "地図で選択",
    "participantsTitle": "自動保護の判定メンバー",
    "statusParticipantsCount": "自動保護の判定メンバー",
    "participantsDescription": "選択したメンバーだけを使って、自動保護をオンにする時刻や通常モードに戻す時刻を判断します。",
    "selectAtLeastOneParticipant": "少なくとも1人のメンバーを選択してください。",
    "mapTitle": "自宅の位置を選択",
    "mapHint": "地図をタップして自宅のピンを移動します。",
    "confirmMapLocation": "自宅の位置を確定",
    "enabledForSelectedParticipants": "選択したメンバーを対象に自動保護を有効にしました。",
    "selectedMembersPermissionHint": "選択したメンバーは、アプリがバックグラウンドでも外出・帰宅を検知できるよう、位置情報を「常に許可」にする必要があります。",
  },
  "de": {
    "chooseOnMap": "Auf Karte auswählen",
    "participantsTitle": "Personen für den Auto-Schutz",
    "statusParticipantsCount": "Personen für den Auto-Schutz",
    "participantsDescription": "Nur ausgewählte Personen bestimmen, wann der Auto-Schutz aktiviert oder auf Normal zurückgestellt wird.",
    "selectAtLeastOneParticipant": "Wähle mindestens eine Person aus.",
    "mapTitle": "Zuhause-Standort auswählen",
    "mapHint": "Tippe auf die Karte, um die Zuhause-Markierung zu verschieben.",
    "confirmMapLocation": "Zuhause-Standort bestätigen",
    "enabledForSelectedParticipants": "Der Auto-Schutz wurde für die ausgewählten Personen aktiviert.",
    "selectedMembersPermissionHint": "Ausgewählte Personen benötigen den Standortzugriff „Immer“, damit Ankunft und Verlassen im Hintergrund erkannt werden.",
  },
  "ru": {
    "chooseOnMap": "Выбрать на карте",
    "participantsTitle": "Участники для автоохраны",
    "statusParticipantsCount": "Участники для автоохраны",
    "participantsDescription": "Только выбранные участники определяют, когда включать автоохрану или возвращать обычный режим.",
    "selectAtLeastOneParticipant": "Выберите хотя бы одного участника.",
    "mapTitle": "Выбрать местоположение дома",
    "mapHint": "Нажмите на карту, чтобы переместить метку дома.",
    "confirmMapLocation": "Подтвердить местоположение дома",
    "enabledForSelectedParticipants": "Автоохрана включена для выбранных участников.",
    "selectedMembersPermissionHint": "Выбранным участникам нужен доступ к геопозиции «Всегда», чтобы уход и возвращение определялись в фоновом режиме.",
  },
  "fr": {
    "chooseOnMap": "Choisir sur la carte",
    "participantsTitle": "Personnes utilisées pour la protection automatique",
    "statusParticipantsCount": "Personnes utilisées pour la protection automatique",
    "participantsDescription": "Seules les personnes sélectionnées déterminent quand activer la protection automatique ou revenir au mode Normal.",
    "selectAtLeastOneParticipant": "Sélectionnez au moins une personne.",
    "mapTitle": "Choisir l’emplacement du domicile",
    "mapHint": "Touchez la carte pour déplacer le repère du domicile.",
    "confirmMapLocation": "Confirmer l’emplacement du domicile",
    "enabledForSelectedParticipants": "La protection automatique a été activée pour les personnes sélectionnées.",
    "selectedMembersPermissionHint": "Les personnes sélectionnées doivent autoriser la localisation « Toujours » pour détecter les départs et les retours en arrière-plan.",
  },
  "es": {
    "chooseOnMap": "Elegir en el mapa",
    "participantsTitle": "Personas para la protección automática",
    "statusParticipantsCount": "Personas para la protección automática",
    "participantsDescription": "Solo las personas seleccionadas se usan para decidir cuándo activar la protección automática o volver al modo Normal.",
    "selectAtLeastOneParticipant": "Selecciona al menos una persona.",
    "mapTitle": "Elegir ubicación de la casa",
    "mapHint": "Toca el mapa para mover el marcador de la casa.",
    "confirmMapLocation": "Confirmar ubicación de la casa",
    "enabledForSelectedParticipants": "La protección automática se activó para las personas seleccionadas.",
    "selectedMembersPermissionHint": "Las personas seleccionadas necesitan el permiso de ubicación «Siempre» para detectar salidas y llegadas en segundo plano.",
  },
  "id": {
    "chooseOnMap": "Pilih di peta",
    "participantsTitle": "Anggota penentu Perlindungan Otomatis",
    "statusParticipantsCount": "Anggota penentu Perlindungan Otomatis",
    "participantsDescription": "Hanya anggota yang dipilih yang digunakan untuk menentukan kapan Perlindungan Otomatis aktif atau kembali ke mode Normal.",
    "selectAtLeastOneParticipant": "Pilih setidaknya satu anggota.",
    "mapTitle": "Pilih lokasi rumah",
    "mapHint": "Ketuk peta untuk memindahkan penanda lokasi rumah.",
    "confirmMapLocation": "Konfirmasi lokasi rumah",
    "enabledForSelectedParticipants": "Perlindungan Otomatis diaktifkan berdasarkan anggota yang dipilih.",
    "selectedMembersPermissionHint": "Anggota yang dipilih memerlukan izin lokasi Selalu agar keberangkatan dan kedatangan dapat terdeteksi saat aplikasi berjalan di latar belakang.",
  },
  "th": {
    "chooseOnMap": "เลือกบนแผนที่",
    "participantsTitle": "สมาชิกที่ใช้กำหนดการป้องกันอัตโนมัติ",
    "statusParticipantsCount": "สมาชิกที่ใช้กำหนดการป้องกันอัตโนมัติ",
    "participantsDescription": "ระบบจะใช้เฉพาะสมาชิกที่เลือกเพื่อตัดสินใจว่าจะเปิดการป้องกันอัตโนมัติหรือกลับสู่โหมดปกติเมื่อใด",
    "selectAtLeastOneParticipant": "เลือกสมาชิกอย่างน้อยหนึ่งคน",
    "mapTitle": "เลือกตำแหน่งบ้าน",
    "mapHint": "แตะแผนที่เพื่อย้ายหมุดตำแหน่งบ้าน",
    "confirmMapLocation": "ยืนยันตำแหน่งบ้าน",
    "enabledForSelectedParticipants": "เปิดการป้องกันอัตโนมัติตามสมาชิกที่เลือกแล้ว",
    "selectedMembersPermissionHint": "สมาชิกที่เลือกต้องอนุญาตตำแหน่งแบบตลอดเวลา เพื่อให้ตรวจจับการออกจากบ้านและกลับบ้านได้ขณะแอปทำงานเบื้องหลัง",
  },
  "ms": {
    "chooseOnMap": "Pilih pada peta",
    "participantsTitle": "Ahli penentu Perlindungan Automatik",
    "statusParticipantsCount": "Ahli penentu Perlindungan Automatik",
    "participantsDescription": "Hanya ahli yang dipilih digunakan untuk menentukan bila Perlindungan Automatik dihidupkan atau kembali ke mod Normal.",
    "selectAtLeastOneParticipant": "Pilih sekurang-kurangnya seorang ahli.",
    "mapTitle": "Pilih lokasi rumah",
    "mapHint": "Ketik peta untuk mengalihkan penanda lokasi rumah.",
    "confirmMapLocation": "Sahkan lokasi rumah",
    "enabledForSelectedParticipants": "Perlindungan Automatik telah dihidupkan berdasarkan ahli yang dipilih.",
    "selectedMembersPermissionHint": "Ahli yang dipilih memerlukan kebenaran lokasi Sentiasa supaya keluar dan pulang dapat dikesan ketika aplikasi berjalan di latar belakang.",
  },
  "fil": {
    "chooseOnMap": "Pumili sa mapa",
    "participantsTitle": "Mga taong batayan ng Awtomatikong Proteksiyon",
    "statusParticipantsCount": "Mga taong batayan ng Awtomatikong Proteksiyon",
    "participantsDescription": "Ang mga napiling tao lamang ang gagamitin upang magpasya kung kailan bubuksan ang Awtomatikong Proteksiyon o ibabalik sa Normal.",
    "selectAtLeastOneParticipant": "Pumili ng kahit isang tao.",
    "mapTitle": "Piliin ang lokasyon ng bahay",
    "mapHint": "I-tap ang mapa upang ilipat ang marker ng bahay.",
    "confirmMapLocation": "Kumpirmahin ang lokasyon ng bahay",
    "enabledForSelectedParticipants": "Na-enable ang Awtomatikong Proteksiyon para sa mga napiling tao.",
    "selectedMembersPermissionHint": "Kailangan ng mga napiling tao ang pahintulot sa lokasyon na Palaging Payagan upang gumana sa background ang pag-detect ng pag-alis at pagdating.",
  },
  "km": {
    "chooseOnMap": "ជ្រើសរើសលើផែនទី",
    "participantsTitle": "សមាជិកសម្រាប់កំណត់ការការពារស្វ័យប្រវត្តិ",
    "statusParticipantsCount": "សមាជិកសម្រាប់កំណត់ការការពារស្វ័យប្រវត្តិ",
    "participantsDescription": "ប្រើតែសមាជិកដែលបានជ្រើសរើស ដើម្បីកំណត់ពេលបើកការការពារស្វ័យប្រវត្តិ ឬត្រឡប់ទៅរបៀបធម្មតា។",
    "selectAtLeastOneParticipant": "សូមជ្រើសរើសសមាជិកយ៉ាងហោចណាស់ម្នាក់។",
    "mapTitle": "ជ្រើសរើសទីតាំងផ្ទះ",
    "mapHint": "ប៉ះលើផែនទីដើម្បីផ្លាស់ទីសញ្ញាទីតាំងផ្ទះ។",
    "confirmMapLocation": "បញ្ជាក់ទីតាំងផ្ទះ",
    "enabledForSelectedParticipants": "បានបើកការការពារស្វ័យប្រវត្តិសម្រាប់សមាជិកដែលបានជ្រើសរើស។",
    "selectedMembersPermissionHint": "សមាជិកដែលបានជ្រើសរើសត្រូវអនុញ្ញាតទីតាំងជានិច្ច ដើម្បីឱ្យការចាកចេញ និងការមកដល់ដំណើរការនៅផ្ទៃខាងក្រោយ។",
  },
  "my": {
    "chooseOnMap": "မြေပုံပေါ်တွင် ရွေးချယ်ပါ",
    "participantsTitle": "အလိုအလျောက်ကာကွယ်မှု ဆုံးဖြတ်မည့် အဖွဲ့ဝင်များ",
    "statusParticipantsCount": "အလိုအလျောက်ကာကွယ်မှု ဆုံးဖြတ်မည့် အဖွဲ့ဝင်များ",
    "participantsDescription": "အလိုအလျောက်ကာကွယ်မှု ဖွင့်မည့်အချိန် သို့မဟုတ် ပုံမှန်မုဒ်သို့ ပြန်မည့်အချိန်ကို ရွေးချယ်ထားသော အဖွဲ့ဝင်များဖြင့်သာ ဆုံးဖြတ်ပါမည်။",
    "selectAtLeastOneParticipant": "အနည်းဆုံး အဖွဲ့ဝင်တစ်ဦးကို ရွေးချယ်ပါ။",
    "mapTitle": "အိမ်တည်နေရာ ရွေးချယ်ပါ",
    "mapHint": "အိမ်တည်နေရာ ပင်ကို ရွှေ့ရန် မြေပုံကို နှိပ်ပါ။",
    "confirmMapLocation": "အိမ်တည်နေရာ အတည်ပြုပါ",
    "enabledForSelectedParticipants": "ရွေးချယ်ထားသော အဖွဲ့ဝင်များအတွက် အလိုအလျောက်ကာကွယ်မှုကို ဖွင့်ထားပါပြီ။",
    "selectedMembersPermissionHint": "အက်ပ်နောက်ခံတွင် အိမ်မှထွက်ခြင်းနှင့် ပြန်ရောက်ခြင်းကို သိရှိနိုင်ရန် ရွေးချယ်ထားသော အဖွဲ့ဝင်များသည် တည်နေရာခွင့်ပြုချက်ကို အမြဲတမ်း ခွင့်ပြုရပါမည်။",
  },
  "lo": {
    "chooseOnMap": "ເລືອກໃນແຜນທີ່",
    "participantsTitle": "ສະມາຊິກສຳລັບກຳນົດການປ້ອງກັນອັດຕະໂນມັດ",
    "statusParticipantsCount": "ສະມາຊິກສຳລັບກຳນົດການປ້ອງກັນອັດຕະໂນມັດ",
    "participantsDescription": "ໃຊ້ສະເພາະສະມາຊິກທີ່ເລືອກເພື່ອຕັດສິນວ່າເມື່ອໃດຈະເປີດການປ້ອງກັນອັດຕະໂນມັດ ຫຼືກັບສູ່ໂໝດປົກກະຕິ.",
    "selectAtLeastOneParticipant": "ກະລຸນາເລືອກສະມາຊິກຢ່າງໜ້ອຍໜຶ່ງຄົນ.",
    "mapTitle": "ເລືອກຕຳແໜ່ງເຮືອນ",
    "mapHint": "ແຕະແຜນທີ່ເພື່ອຍ້າຍໝຸດຕຳແໜ່ງເຮືອນ.",
    "confirmMapLocation": "ຢືນຢັນຕຳແໜ່ງເຮືອນ",
    "enabledForSelectedParticipants": "ເປີດການປ້ອງກັນອັດຕະໂນມັດສຳລັບສະມາຊິກທີ່ເລືອກແລ້ວ.",
    "selectedMembersPermissionHint": "ສະມາຊິກທີ່ເລືອກຕ້ອງອະນຸຍາດຕຳແໜ່ງແບບຕະຫຼອດເວລາ ເພື່ອໃຫ້ການອອກແລະກັບບ້ານເຮັດວຽກໃນພື້ນຫຼັງ.",
  },
  "ta": {
    "chooseOnMap": "வரைபடத்தில் தேர்வு செய்",
    "participantsTitle": "தானியங்கு பாதுகாப்பை நிர்ணயிக்கும் உறுப்பினர்கள்",
    "statusParticipantsCount": "தானியங்கு பாதுகாப்பை நிர்ணயிக்கும் உறுப்பினர்கள்",
    "participantsDescription": "தானியங்கு பாதுகாப்பு எப்போது இயங்க வேண்டும் அல்லது இயல்பு நிலைக்குத் திரும்ப வேண்டும் என்பதைத் தீர்மானிக்க தேர்ந்தெடுக்கப்பட்ட உறுப்பினர்கள் மட்டுமே பயன்படுத்தப்படுவர்.",
    "selectAtLeastOneParticipant": "குறைந்தது ஒரு உறுப்பினரைத் தேர்வு செய்யுங்கள்.",
    "mapTitle": "வீட்டு இருப்பிடத்தைத் தேர்வு செய்",
    "mapHint": "வீட்டு குறியீட்டை நகர்த்த வரைபடத்தைத் தட்டுங்கள்.",
    "confirmMapLocation": "வீட்டு இருப்பிடத்தை உறுதிப்படுத்து",
    "enabledForSelectedParticipants": "தேர்ந்தெடுக்கப்பட்ட உறுப்பினர்களுக்கு தானியங்கு பாதுகாப்பு இயக்கப்பட்டது.",
    "selectedMembersPermissionHint": "செயலி பின்னணியில் இருக்கும் போது வெளியேறுதல் மற்றும் வருகையை கண்டறிய தேர்ந்தெடுக்கப்பட்ட உறுப்பினர்கள் இருப்பிட அனுமதியை எப்போதும் அனுமதிக்க வேண்டும்.",
  },
  "pt": {
    "chooseOnMap": "Escolher no mapa",
    "participantsTitle": "Pessoas usadas na Proteção Automática",
    "statusParticipantsCount": "Pessoas usadas na Proteção Automática",
    "participantsDescription": "Apenas as pessoas selecionadas são usadas para decidir quando ativar a Proteção Automática ou voltar ao modo Normal.",
    "selectAtLeastOneParticipant": "Selecione pelo menos uma pessoa.",
    "mapTitle": "Escolher localização da casa",
    "mapHint": "Toque no mapa para mover o marcador da casa.",
    "confirmMapLocation": "Confirmar localização da casa",
    "enabledForSelectedParticipants": "A Proteção Automática foi ativada para as pessoas selecionadas.",
    "selectedMembersPermissionHint": "As pessoas selecionadas precisam da permissão de localização Sempre para detetar saídas e chegadas em segundo plano.",
  },
  "tet": {
    "chooseOnMap": "Hili iha mapa",
    "participantsTitle": "Ema sira ba Protesaun Automátika",
    "statusParticipantsCount": "Ema sira ba Protesaun Automátika",
    "participantsDescription": "Ema ne’ebé hili de’it mak uza atu determina bainhira Protesaun Automátika liga ka fila ba modu Normal.",
    "selectAtLeastOneParticipant": "Hili pelumenus ema ida.",
    "mapTitle": "Hili lokalizasaun uma",
    "mapHint": "Toka mapa atu muda marka lokalizasaun uma.",
    "confirmMapLocation": "Konfirma lokalizasaun uma",
    "enabledForSelectedParticipants": "Protesaun Automátika ativa ona ba ema sira ne’ebé hili.",
    "selectedMembersPermissionHint": "Ema sira ne’ebé hili presiza permisaun lokalizasaun Sempre atu deteta sai no fila iha background.",
  },
  "it": {
    "chooseOnMap": "Scegli sulla mappa",
    "participantsTitle": "Persone usate per la Protezione automatica",
    "statusParticipantsCount": "Persone usate per la Protezione automatica",
    "participantsDescription": "Solo le persone selezionate vengono usate per decidere quando attivare la Protezione automatica o tornare alla modalità Normale.",
    "selectAtLeastOneParticipant": "Seleziona almeno una persona.",
    "mapTitle": "Scegli la posizione della casa",
    "mapHint": "Tocca la mappa per spostare il segnaposto della casa.",
    "confirmMapLocation": "Conferma la posizione della casa",
    "enabledForSelectedParticipants": "La Protezione automatica è stata attivata per le persone selezionate.",
    "selectedMembersPermissionHint": "Le persone selezionate devono consentire sempre la posizione per rilevare partenze e arrivi in background.",
  },
  "pl": {
    "chooseOnMap": "Wybierz na mapie",
    "participantsTitle": "Osoby używane przez ochronę automatyczną",
    "statusParticipantsCount": "Osoby używane przez ochronę automatyczną",
    "participantsDescription": "Tylko wybrane osoby decydują, kiedy włączyć ochronę automatyczną lub wrócić do trybu Normalnego.",
    "selectAtLeastOneParticipant": "Wybierz co najmniej jedną osobę.",
    "mapTitle": "Wybierz lokalizację domu",
    "mapHint": "Dotknij mapy, aby przesunąć znacznik domu.",
    "confirmMapLocation": "Potwierdź lokalizację domu",
    "enabledForSelectedParticipants": "Ochrona automatyczna została włączona dla wybranych osób.",
    "selectedMembersPermissionHint": "Wybrane osoby muszą zezwolić na dostęp do lokalizacji „Zawsze”, aby wykrywanie wyjścia i powrotu działało w tle.",
  },
  "nl": {
    "chooseOnMap": "Kiezen op kaart",
    "participantsTitle": "Personen voor Automatische beveiliging",
    "statusParticipantsCount": "Personen voor Automatische beveiliging",
    "participantsDescription": "Alleen geselecteerde personen bepalen wanneer Automatische beveiliging wordt ingeschakeld of teruggaat naar Normaal.",
    "selectAtLeastOneParticipant": "Selecteer minstens één persoon.",
    "mapTitle": "Thuislocatie kiezen",
    "mapHint": "Tik op de kaart om de thuismarkering te verplaatsen.",
    "confirmMapLocation": "Thuislocatie bevestigen",
    "enabledForSelectedParticipants": "Automatische beveiliging is ingeschakeld voor de geselecteerde personen.",
    "selectedMembersPermissionHint": "Geselecteerde personen hebben locatietoegang Altijd nodig om vertrek en aankomst op de achtergrond te detecteren.",
  },
  "cs": {
    "chooseOnMap": "Vybrat na mapě",
    "participantsTitle": "Osoby pro automatickou ochranu",
    "statusParticipantsCount": "Osoby pro automatickou ochranu",
    "participantsDescription": "Pouze vybrané osoby určují, kdy se automatická ochrana zapne nebo vrátí do normálního režimu.",
    "selectAtLeastOneParticipant": "Vyberte alespoň jednu osobu.",
    "mapTitle": "Vybrat polohu domova",
    "mapHint": "Klepnutím na mapu přesuňte značku domova.",
    "confirmMapLocation": "Potvrdit polohu domova",
    "enabledForSelectedParticipants": "Automatická ochrana byla zapnuta pro vybrané osoby.",
    "selectedMembersPermissionHint": "Vybrané osoby musí povolit přístup k poloze Vždy, aby odchody a příchody fungovaly na pozadí.",
  },
  "sk": {
    "chooseOnMap": "Vybrať na mape",
    "participantsTitle": "Osoby pre automatickú ochranu",
    "statusParticipantsCount": "Osoby pre automatickú ochranu",
    "participantsDescription": "Iba vybrané osoby určujú, kedy sa automatická ochrana zapne alebo vráti do normálneho režimu.",
    "selectAtLeastOneParticipant": "Vyberte aspoň jednu osobu.",
    "mapTitle": "Vybrať polohu domova",
    "mapHint": "Ťuknutím na mapu presuňte značku domova.",
    "confirmMapLocation": "Potvrdiť polohu domova",
    "enabledForSelectedParticipants": "Automatická ochrana bola zapnutá pre vybrané osoby.",
    "selectedMembersPermissionHint": "Vybrané osoby musia povoliť polohu Vždy, aby odchody a príchody fungovali na pozadí.",
  },
  "uk": {
    "chooseOnMap": "Вибрати на карті",
    "participantsTitle": "Учасники для автоохорони",
    "statusParticipantsCount": "Учасники для автоохорони",
    "participantsDescription": "Лише вибрані учасники визначають, коли вмикати автоохорону або повертати звичайний режим.",
    "selectAtLeastOneParticipant": "Виберіть принаймні одного учасника.",
    "mapTitle": "Вибрати розташування дому",
    "mapHint": "Торкніться карти, щоб перемістити позначку дому.",
    "confirmMapLocation": "Підтвердити розташування дому",
    "enabledForSelectedParticipants": "Автоохорону ввімкнено для вибраних учасників.",
    "selectedMembersPermissionHint": "Вибраним учасникам потрібен доступ до геопозиції «Завжди», щоб вихід і повернення визначалися у фоновому режимі.",
  },
  "ro": {
    "chooseOnMap": "Alege pe hartă",
    "participantsTitle": "Persoane pentru Protecția automată",
    "statusParticipantsCount": "Persoane pentru Protecția automată",
    "participantsDescription": "Doar persoanele selectate sunt folosite pentru a decide când se activează Protecția automată sau se revine la modul Normal.",
    "selectAtLeastOneParticipant": "Selectează cel puțin o persoană.",
    "mapTitle": "Alege locația casei",
    "mapHint": "Atinge harta pentru a muta marcajul casei.",
    "confirmMapLocation": "Confirmă locația casei",
    "enabledForSelectedParticipants": "Protecția automată a fost activată pentru persoanele selectate.",
    "selectedMembersPermissionHint": "Persoanele selectate au nevoie de permisiunea de localizare Întotdeauna pentru detectarea plecărilor și sosirilor în fundal.",
  },
  "hu": {
    "chooseOnMap": "Kiválasztás a térképen",
    "participantsTitle": "Az automatikus védelemhez használt személyek",
    "statusParticipantsCount": "Az automatikus védelemhez használt személyek",
    "participantsDescription": "Csak a kiválasztott személyek alapján dől el, mikor kapcsoljon be az automatikus védelem, vagy mikor térjen vissza Normál módba.",
    "selectAtLeastOneParticipant": "Válassz ki legalább egy személyt.",
    "mapTitle": "Otthon helyének kiválasztása",
    "mapHint": "Érintsd meg a térképet az otthon jelölőjének áthelyezéséhez.",
    "confirmMapLocation": "Otthon helyének megerősítése",
    "enabledForSelectedParticipants": "Az automatikus védelem bekapcsolt a kiválasztott személyekhez.",
    "selectedMembersPermissionHint": "A kiválasztott személyeknek Mindig helyhozzáférést kell engedélyezniük, hogy a távozás és érkezés a háttérben is működjön.",
  },
  "bg": {
    "chooseOnMap": "Избор на картата",
    "participantsTitle": "Хора за автоматичната защита",
    "statusParticipantsCount": "Хора за автоматичната защита",
    "participantsDescription": "Само избраните хора определят кога автоматичната защита да се включи или да се върне в Нормален режим.",
    "selectAtLeastOneParticipant": "Изберете поне един човек.",
    "mapTitle": "Избор на местоположение на дома",
    "mapHint": "Докоснете картата, за да преместите маркера на дома.",
    "confirmMapLocation": "Потвърждаване на местоположението",
    "enabledForSelectedParticipants": "Автоматичната защита е включена за избраните хора.",
    "selectedMembersPermissionHint": "Избраните хора трябва да разрешат достъп до местоположението Винаги, за да се откриват тръгване и пристигане във фонов режим.",
  },
  "hr": {
    "chooseOnMap": "Odaberi na karti",
    "participantsTitle": "Osobe za automatsku zaštitu",
    "statusParticipantsCount": "Osobe za automatsku zaštitu",
    "participantsDescription": "Samo odabrane osobe određuju kada se automatska zaštita uključuje ili vraća u Normalni način.",
    "selectAtLeastOneParticipant": "Odaberite barem jednu osobu.",
    "mapTitle": "Odaberi lokaciju doma",
    "mapHint": "Dodirnite kartu da biste premjestili oznaku doma.",
    "confirmMapLocation": "Potvrdi lokaciju doma",
    "enabledForSelectedParticipants": "Automatska zaštita uključena je za odabrane osobe.",
    "selectedMembersPermissionHint": "Odabrane osobe moraju dopustiti lokaciju Uvijek kako bi se odlasci i dolasci otkrivali u pozadini.",
  },
  "sr": {
    "chooseOnMap": "Изабери на мапи",
    "participantsTitle": "Особе за аутоматску заштиту",
    "statusParticipantsCount": "Особе за аутоматску заштиту",
    "participantsDescription": "Само изабране особе одређују када се аутоматска заштита укључује или враћа у Нормални режим.",
    "selectAtLeastOneParticipant": "Изаберите бар једну особу.",
    "mapTitle": "Изабери локацију дома",
    "mapHint": "Додирните мапу да бисте померили ознаку дома.",
    "confirmMapLocation": "Потврди локацију дома",
    "enabledForSelectedParticipants": "Аутоматска заштита је укључена за изабране особе.",
    "selectedMembersPermissionHint": "Изабране особе морају дозволити локацију Увек како би се одласци и доласци откривали у позадини.",
  },
  "bs": {
    "chooseOnMap": "Odaberi na karti",
    "participantsTitle": "Osobe za automatsku zaštitu",
    "statusParticipantsCount": "Osobe za automatsku zaštitu",
    "participantsDescription": "Samo odabrane osobe određuju kada se automatska zaštita uključuje ili vraća u Normalni način.",
    "selectAtLeastOneParticipant": "Odaberite najmanje jednu osobu.",
    "mapTitle": "Odaberi lokaciju doma",
    "mapHint": "Dodirnite kartu da pomjerite oznaku doma.",
    "confirmMapLocation": "Potvrdi lokaciju doma",
    "enabledForSelectedParticipants": "Automatska zaštita je uključena za odabrane osobe.",
    "selectedMembersPermissionHint": "Odabrane osobe moraju dozvoliti lokaciju Uvijek kako bi se odlasci i dolasci prepoznavali u pozadini.",
  },
  "sl": {
    "chooseOnMap": "Izberi na zemljevidu",
    "participantsTitle": "Osebe za samodejno zaščito",
    "statusParticipantsCount": "Osebe za samodejno zaščito",
    "participantsDescription": "Samo izbrane osebe določajo, kdaj se samodejna zaščita vklopi ali vrne v običajni način.",
    "selectAtLeastOneParticipant": "Izberite vsaj eno osebo.",
    "mapTitle": "Izberi lokacijo doma",
    "mapHint": "Tapnite zemljevid, da premaknete oznako doma.",
    "confirmMapLocation": "Potrdi lokacijo doma",
    "enabledForSelectedParticipants": "Samodejna zaščita je bila vklopljena za izbrane osebe.",
    "selectedMembersPermissionHint": "Izbrane osebe morajo dovoliti lokacijo Vedno, da se odhodi in prihodi zaznajo v ozadju.",
  },
  "mk": {
    "chooseOnMap": "Избери на карта",
    "participantsTitle": "Лица за автоматска заштита",
    "statusParticipantsCount": "Лица за автоматска заштита",
    "participantsDescription": "Само избраните лица одредуваат кога автоматската заштита се вклучува или се враќа во Нормален режим.",
    "selectAtLeastOneParticipant": "Изберете најмалку едно лице.",
    "mapTitle": "Избери локација на домот",
    "mapHint": "Допрете ја картата за да ја преместите ознаката на домот.",
    "confirmMapLocation": "Потврди ја локацијата на домот",
    "enabledForSelectedParticipants": "Автоматската заштита е вклучена за избраните лица.",
    "selectedMembersPermissionHint": "Избраните лица мора да дозволат локација Секогаш за заминувањата и пристигнувањата да се откриваат во заднина.",
  },
  "sq": {
    "chooseOnMap": "Zgjidh në hartë",
    "participantsTitle": "Personat për Mbrojtjen automatike",
    "statusParticipantsCount": "Personat për Mbrojtjen automatike",
    "participantsDescription": "Vetëm personat e zgjedhur përdoren për të vendosur kur aktivizohet Mbrojtja automatike ose kur kthehet në modalitetin Normal.",
    "selectAtLeastOneParticipant": "Zgjidh të paktën një person.",
    "mapTitle": "Zgjidh vendndodhjen e shtëpisë",
    "mapHint": "Prek hartën për të lëvizur shenjuesin e shtëpisë.",
    "confirmMapLocation": "Konfirmo vendndodhjen e shtëpisë",
    "enabledForSelectedParticipants": "Mbrojtja automatike u aktivizua për personat e zgjedhur.",
    "selectedMembersPermissionHint": "Personat e zgjedhur duhet të lejojnë vendndodhjen Gjithmonë që largimet dhe mbërritjet të zbulohen në sfond.",
  },
  "el": {
    "chooseOnMap": "Επιλογή στον χάρτη",
    "participantsTitle": "Άτομα για την Αυτόματη προστασία",
    "statusParticipantsCount": "Άτομα για την Αυτόματη προστασία",
    "participantsDescription": "Μόνο τα επιλεγμένα άτομα χρησιμοποιούνται για να αποφασιστεί πότε ενεργοποιείται η Αυτόματη προστασία ή επιστρέφει σε Κανονική λειτουργία.",
    "selectAtLeastOneParticipant": "Επιλέξτε τουλάχιστον ένα άτομο.",
    "mapTitle": "Επιλογή τοποθεσίας σπιτιού",
    "mapHint": "Πατήστε τον χάρτη για να μετακινήσετε τον δείκτη του σπιτιού.",
    "confirmMapLocation": "Επιβεβαίωση τοποθεσίας σπιτιού",
    "enabledForSelectedParticipants": "Η Αυτόματη προστασία ενεργοποιήθηκε για τα επιλεγμένα άτομα.",
    "selectedMembersPermissionHint": "Τα επιλεγμένα άτομα χρειάζονται άδεια τοποθεσίας Πάντα, ώστε οι αναχωρήσεις και οι αφίξεις να εντοπίζονται στο παρασκήνιο.",
  },
  "tr": {
    "chooseOnMap": "Haritadan seç",
    "participantsTitle": "Otomatik Koruma için kişiler",
    "statusParticipantsCount": "Otomatik Koruma için kişiler",
    "participantsDescription": "Yalnızca seçilen kişiler, Otomatik Korumanın ne zaman açılacağını veya Normal moda dönüleceğini belirlemek için kullanılır.",
    "selectAtLeastOneParticipant": "En az bir kişi seçin.",
    "mapTitle": "Ev konumunu seç",
    "mapHint": "Ev işaretçisini taşımak için haritaya dokunun.",
    "confirmMapLocation": "Ev konumunu onayla",
    "enabledForSelectedParticipants": "Otomatik Koruma seçilen kişiler için etkinleştirildi.",
    "selectedMembersPermissionHint": "Seçilen kişilerin, ayrılış ve varışların arka planda algılanması için konum iznini Her Zaman olarak vermesi gerekir.",
  },
  "sv": {
    "chooseOnMap": "Välj på kartan",
    "participantsTitle": "Personer för Automatiskt skydd",
    "statusParticipantsCount": "Personer för Automatiskt skydd",
    "participantsDescription": "Endast valda personer används för att avgöra när Automatiskt skydd aktiveras eller återgår till Normalläge.",
    "selectAtLeastOneParticipant": "Välj minst en person.",
    "mapTitle": "Välj hemposition",
    "mapHint": "Tryck på kartan för att flytta hemmarkören.",
    "confirmMapLocation": "Bekräfta hemposition",
    "enabledForSelectedParticipants": "Automatiskt skydd aktiverades för de valda personerna.",
    "selectedMembersPermissionHint": "Valda personer behöver platsbehörigheten Alltid för att avfärd och ankomst ska upptäckas i bakgrunden.",
  },
  "da": {
    "chooseOnMap": "Vælg på kortet",
    "participantsTitle": "Personer til Automatisk beskyttelse",
    "statusParticipantsCount": "Personer til Automatisk beskyttelse",
    "participantsDescription": "Kun valgte personer bruges til at afgøre, hvornår Automatisk beskyttelse aktiveres eller vender tilbage til Normal.",
    "selectAtLeastOneParticipant": "Vælg mindst én person.",
    "mapTitle": "Vælg hjemmets placering",
    "mapHint": "Tryk på kortet for at flytte hjemmemarkøren.",
    "confirmMapLocation": "Bekræft hjemmets placering",
    "enabledForSelectedParticipants": "Automatisk beskyttelse blev aktiveret for de valgte personer.",
    "selectedMembersPermissionHint": "Valgte personer skal give placeringstilladelsen Altid, så afgang og ankomst kan registreres i baggrunden.",
  },
  "nb": {
    "chooseOnMap": "Velg på kartet",
    "participantsTitle": "Personer for Automatisk beskyttelse",
    "statusParticipantsCount": "Personer for Automatisk beskyttelse",
    "participantsDescription": "Bare valgte personer brukes til å avgjøre når Automatisk beskyttelse slås på eller går tilbake til Normal.",
    "selectAtLeastOneParticipant": "Velg minst én person.",
    "mapTitle": "Velg hjemmeposisjon",
    "mapHint": "Trykk på kartet for å flytte hjemmemarkøren.",
    "confirmMapLocation": "Bekreft hjemmeposisjon",
    "enabledForSelectedParticipants": "Automatisk beskyttelse ble slått på for de valgte personene.",
    "selectedMembersPermissionHint": "Valgte personer trenger posisjonstillatelsen Alltid slik at avreise og ankomst kan oppdages i bakgrunnen.",
  },
  "fi": {
    "chooseOnMap": "Valitse kartalta",
    "participantsTitle": "Automaattiseen suojaukseen käytettävät henkilöt",
    "statusParticipantsCount": "Automaattiseen suojaukseen käytettävät henkilöt",
    "participantsDescription": "Vain valitut henkilöt määrittävät, milloin Automaattinen suojaus otetaan käyttöön tai palataan Normaali-tilaan.",
    "selectAtLeastOneParticipant": "Valitse vähintään yksi henkilö.",
    "mapTitle": "Valitse kodin sijainti",
    "mapHint": "Siirrä kodin merkkiä napauttamalla karttaa.",
    "confirmMapLocation": "Vahvista kodin sijainti",
    "enabledForSelectedParticipants": "Automaattinen suojaus otettiin käyttöön valituille henkilöille.",
    "selectedMembersPermissionHint": "Valitut henkilöt tarvitsevat sijaintiluvan Aina, jotta lähtö ja saapuminen voidaan havaita taustalla.",
  },
  "is": {
    "chooseOnMap": "Velja á korti",
    "participantsTitle": "Einstaklingar fyrir Sjálfvirka vernd",
    "statusParticipantsCount": "Einstaklingar fyrir Sjálfvirka vernd",
    "participantsDescription": "Aðeins valdir einstaklingar ráða hvenær Sjálfvirk vernd kveikir eða fer aftur í Venjulega stillingu.",
    "selectAtLeastOneParticipant": "Veldu að minnsta kosti einn einstakling.",
    "mapTitle": "Velja staðsetningu heimilis",
    "mapHint": "Pikkaðu á kortið til að færa heimilismerkið.",
    "confirmMapLocation": "Staðfesta staðsetningu heimilis",
    "enabledForSelectedParticipants": "Sjálfvirk vernd var virkjuð fyrir valda einstaklinga.",
    "selectedMembersPermissionHint": "Valdir einstaklingar þurfa staðsetningarheimildina Alltaf svo brottför og heimkoma greinist í bakgrunni.",
  },
  "et": {
    "chooseOnMap": "Vali kaardil",
    "participantsTitle": "Automaatkaitse jaoks kasutatavad inimesed",
    "statusParticipantsCount": "Automaatkaitse jaoks kasutatavad inimesed",
    "participantsDescription": "Ainult valitud inimesed määravad, millal Automaatkaitse sisse lülitub või naaseb Tavarežiimi.",
    "selectAtLeastOneParticipant": "Vali vähemalt üks inimene.",
    "mapTitle": "Vali kodu asukoht",
    "mapHint": "Kodu märgi liigutamiseks puuduta kaarti.",
    "confirmMapLocation": "Kinnita kodu asukoht",
    "enabledForSelectedParticipants": "Automaatkaitse lülitati valitud inimeste jaoks sisse.",
    "selectedMembersPermissionHint": "Valitud inimesed peavad lubama asukoha Alati, et lahkumist ja saabumist saaks taustal tuvastada.",
  },
  "lv": {
    "chooseOnMap": "Izvēlēties kartē",
    "participantsTitle": "Personas automātiskajai aizsardzībai",
    "statusParticipantsCount": "Personas automātiskajai aizsardzībai",
    "participantsDescription": "Tikai izvēlētās personas nosaka, kad ieslēgt automātisko aizsardzību vai atgriezties Normālajā režīmā.",
    "selectAtLeastOneParticipant": "Izvēlieties vismaz vienu personu.",
    "mapTitle": "Izvēlēties mājas atrašanās vietu",
    "mapHint": "Pieskarieties kartei, lai pārvietotu mājas marķieri.",
    "confirmMapLocation": "Apstiprināt mājas atrašanās vietu",
    "enabledForSelectedParticipants": "Automātiskā aizsardzība ieslēgta izvēlētajām personām.",
    "selectedMembersPermissionHint": "Izvēlētajām personām nepieciešama atrašanās vietas atļauja Vienmēr, lai aiziešana un atgriešanās tiktu noteikta fonā.",
  },
  "lt": {
    "chooseOnMap": "Pasirinkti žemėlapyje",
    "participantsTitle": "Asmenys automatinei apsaugai",
    "statusParticipantsCount": "Asmenys automatinei apsaugai",
    "participantsDescription": "Tik pasirinkti asmenys lemia, kada įjungti Automatinę apsaugą arba grįžti į Įprastą režimą.",
    "selectAtLeastOneParticipant": "Pasirinkite bent vieną asmenį.",
    "mapTitle": "Pasirinkti namų vietą",
    "mapHint": "Palieskite žemėlapį, kad perkeltumėte namų žymeklį.",
    "confirmMapLocation": "Patvirtinti namų vietą",
    "enabledForSelectedParticipants": "Automatinė apsauga įjungta pasirinktiems asmenims.",
    "selectedMembersPermissionHint": "Pasirinktiems asmenims reikia vietos leidimo Visada, kad išvykimas ir grįžimas būtų aptinkami fone.",
  },
  "ga": {
    "chooseOnMap": "Roghnaigh ar an léarscáil",
    "participantsTitle": "Daoine don Chosaint Uathoibríoch",
    "statusParticipantsCount": "Daoine don Chosaint Uathoibríoch",
    "participantsDescription": "Is iad na daoine roghnaithe amháin a úsáidtear chun cinneadh a dhéanamh cathain a chuirtear an Chosaint Uathoibríoch ar siúl nó a fhilltear ar an ngnáthmhód.",
    "selectAtLeastOneParticipant": "Roghnaigh duine amháin ar a laghad.",
    "mapTitle": "Roghnaigh suíomh an tí",
    "mapHint": "Tapáil an léarscáil chun marcóir an tí a bhogadh.",
    "confirmMapLocation": "Deimhnigh suíomh an tí",
    "enabledForSelectedParticipants": "Cumasaíodh an Chosaint Uathoibríoch do na daoine roghnaithe.",
    "selectedMembersPermissionHint": "Teastaíonn cead suímh I gCónaí ó na daoine roghnaithe chun imeacht agus teacht a bhrath sa chúlra.",
  },
  "mt": {
    "chooseOnMap": "Agħżel fuq il-mappa",
    "participantsTitle": "Persuni għall-Protezzjoni Awtomatika",
    "statusParticipantsCount": "Persuni għall-Protezzjoni Awtomatika",
    "participantsDescription": "Il-persuni magħżula biss jintużaw biex jiġi deċiż meta tinxtegħel il-Protezzjoni Awtomatika jew terġa’ lura għall-modalità Normali.",
    "selectAtLeastOneParticipant": "Agħżel mill-inqas persuna waħda.",
    "mapTitle": "Agħżel il-post tad-dar",
    "mapHint": "Tektek il-mappa biex iċċaqlaq il-marka tad-dar.",
    "confirmMapLocation": "Ikkonferma l-post tad-dar",
    "enabledForSelectedParticipants": "Il-Protezzjoni Awtomatika nxtegħlet għall-persuni magħżula.",
    "selectedMembersPermissionHint": "Il-persuni magħżula jeħtieġu permess tal-post Dejjem sabiex it-tluq u l-wasla jiġu skoperti fl-isfond.",
  },
  "be": {
    "chooseOnMap": "Выбраць на карце",
    "participantsTitle": "Удзельнікі для аўтааховы",
    "statusParticipantsCount": "Удзельнікі для аўтааховы",
    "participantsDescription": "Толькі выбраныя ўдзельнікі вызначаюць, калі ўключаць аўтаахову або вяртаць звычайны рэжым.",
    "selectAtLeastOneParticipant": "Выберыце хаця б аднаго ўдзельніка.",
    "mapTitle": "Выбраць месцазнаходжанне дома",
    "mapHint": "Націсніце на карту, каб перамясціць пазнаку дома.",
    "confirmMapLocation": "Пацвердзіць месцазнаходжанне дома",
    "enabledForSelectedParticipants": "Аўтаахова ўключана для выбраных удзельнікаў.",
    "selectedMembersPermissionHint": "Выбраным удзельнікам патрэбны доступ да месцазнаходжання «Заўсёды», каб выхад і вяртанне вызначаліся ў фоне.",
  },
  "lb": {
    "chooseOnMap": "Op der Kaart auswielen",
    "participantsTitle": "Persoune fir den Automatesche Schutz",
    "statusParticipantsCount": "Persoune fir den Automatesche Schutz",
    "participantsDescription": "Nëmmen déi ausgewielte Persoune bestëmmen, wéini den Automatesche Schutz aktivéiert gëtt oder zeréck op Normal wiesselt.",
    "selectAtLeastOneParticipant": "Wielt op d’mannst eng Persoun.",
    "mapTitle": "Heemstanduert auswielen",
    "mapHint": "Tippt op d’Kaart, fir d’Heemmarkéierung ze verréckelen.",
    "confirmMapLocation": "Heemstanduert confirméieren",
    "enabledForSelectedParticipants": "Den Automatesche Schutz gouf fir déi ausgewielte Persounen aktivéiert.",
    "selectedMembersPermissionHint": "Déi ausgewielte Persoune brauchen d’Standuertberechtegung Ëmmer, fir Fortgoen an Ukunft am Hannergrond z’erkennen.",
  },
  "ca": {
    "chooseOnMap": "Triar al mapa",
    "participantsTitle": "Persones per a la Protecció automàtica",
    "statusParticipantsCount": "Persones per a la Protecció automàtica",
    "participantsDescription": "Només les persones seleccionades s’utilitzen per decidir quan s’activa la Protecció automàtica o es torna al mode Normal.",
    "selectAtLeastOneParticipant": "Selecciona almenys una persona.",
    "mapTitle": "Triar la ubicació de casa",
    "mapHint": "Toca el mapa per moure el marcador de casa.",
    "confirmMapLocation": "Confirmar la ubicació de casa",
    "enabledForSelectedParticipants": "La Protecció automàtica s’ha activat per a les persones seleccionades.",
    "selectedMembersPermissionHint": "Les persones seleccionades necessiten el permís d’ubicació Sempre perquè les sortides i arribades es detectin en segon pla.",
  },
  "cnr": {
    "chooseOnMap": "Izaberi na mapi",
    "participantsTitle": "Osobe za automatsku zaštitu",
    "statusParticipantsCount": "Osobe za automatsku zaštitu",
    "participantsDescription": "Samo izabrane osobe određuju kada se automatska zaštita uključuje ili vraća u Normalni režim.",
    "selectAtLeastOneParticipant": "Izaberite najmanje jednu osobu.",
    "mapTitle": "Izaberi lokaciju doma",
    "mapHint": "Dodirnite mapu da pomjerite oznaku doma.",
    "confirmMapLocation": "Potvrdi lokaciju doma",
    "enabledForSelectedParticipants": "Automatska zaštita je uključena za izabrane osobe.",
    "selectedMembersPermissionHint": "Izabrane osobe moraju dozvoliti lokaciju Uvijek kako bi se odlasci i dolasci prepoznavali u pozadini.",
  },
  "hy": {
    "chooseOnMap": "Ընտրել քարտեզի վրա",
    "participantsTitle": "Ավտոմատ պաշտպանության համար օգտագործվող անձինք",
    "statusParticipantsCount": "Ավտոմատ պաշտպանության համար օգտագործվող անձինք",
    "participantsDescription": "Միայն ընտրված անձինք են օգտագործվում որոշելու համար, թե երբ միացնել Ավտոմատ պաշտպանությունը կամ վերադառնալ Սովորական ռեժիմին։",
    "selectAtLeastOneParticipant": "Ընտրեք առնվազն մեկ անձ։",
    "mapTitle": "Ընտրել տան տեղադրությունը",
    "mapHint": "Հպեք քարտեզին՝ տան նշիչը տեղափոխելու համար։",
    "confirmMapLocation": "Հաստատել տան տեղադրությունը",
    "enabledForSelectedParticipants": "Ավտոմատ պաշտպանությունը միացվել է ընտրված անձանց համար։",
    "selectedMembersPermissionHint": "Ընտրված անձանց անհրաժեշտ է «Միշտ» տեղադրության թույլտվություն, որպեսզի հեռանալն ու վերադառնալը հայտնաբերվեն հետին պլանում։",
  },
  "ka": {
    "chooseOnMap": "რუკაზე არჩევა",
    "participantsTitle": "ავტომატური დაცვისთვის გამოყენებული პირები",
    "statusParticipantsCount": "ავტომატური დაცვისთვის გამოყენებული პირები",
    "participantsDescription": "მხოლოდ არჩეული პირები გამოიყენება იმის დასადგენად, როდის ჩაირთოს ავტომატური დაცვა ან დაბრუნდეს ჩვეულებრივ რეჟიმში.",
    "selectAtLeastOneParticipant": "აირჩიეთ მინიმუმ ერთი პირი.",
    "mapTitle": "სახლის მდებარეობის არჩევა",
    "mapHint": "შეეხეთ რუკას სახლის ნიშნულის გადასაადგილებლად.",
    "confirmMapLocation": "სახლის მდებარეობის დადასტურება",
    "enabledForSelectedParticipants": "ავტომატური დაცვა ჩაირთო არჩეული პირებისთვის.",
    "selectedMembersPermissionHint": "არჩეულ პირებს სჭირდებათ მდებარეობის ნებართვა „ყოველთვის“, რათა გასვლა და დაბრუნება ფონურ რეჟიმში გამოვლინდეს.",
  },
  "az": {
    "chooseOnMap": "Xəritədə seç",
    "participantsTitle": "Avtomatik Qoruma üçün şəxslər",
    "statusParticipantsCount": "Avtomatik Qoruma üçün şəxslər",
    "participantsDescription": "Yalnız seçilmiş şəxslər Avtomatik Qorumanın nə vaxt açılacağını və ya Normal rejimə qayıdacağını müəyyən etmək üçün istifadə olunur.",
    "selectAtLeastOneParticipant": "Ən azı bir şəxsi seçin.",
    "mapTitle": "Ev məkanını seç",
    "mapHint": "Ev nişanını köçürmək üçün xəritəyə toxunun.",
    "confirmMapLocation": "Ev məkanını təsdiqlə",
    "enabledForSelectedParticipants": "Avtomatik Qoruma seçilmiş şəxslər üçün aktiv edildi.",
    "selectedMembersPermissionHint": "Seçilmiş şəxslər gediş və gəlişin arxa planda aşkarlanması üçün məkan icazəsini Həmişə verməlidir.",
  },
};

const Map<String, Map<String, String>> _autoAwayControlTranslations = {
  "vi": {
    "allParticipants": "Tất cả thành viên",
    "searchHint": "Tìm địa chỉ hoặc địa điểm",
    "noSearchResults": "Không tìm thấy vị trí phù hợp.",
    "searchFailed": "Không thể tìm vị trí. Hãy thử lại.",
    "savedPermissionRequired": "Đã lưu cài đặt. Thiết bị này vẫn cần quyền vị trí Luôn cho phép.",
  },
  "en": {
    "allParticipants": "All members",
    "searchHint": "Search for an address or place",
    "noSearchResults": "No matching location was found.",
    "searchFailed": "Unable to search for a location. Try again.",
    "savedPermissionRequired": "Settings saved. This device still needs Always location permission.",
  },
  "zh": {
    "allParticipants": "所有成员",
    "searchHint": "搜索地址或地点",
    "noSearchResults": "未找到匹配的位置。",
    "searchFailed": "无法搜索位置，请重试。",
    "savedPermissionRequired": "设置已保存。此设备仍需“始终允许”位置权限。",
  },
  "ko": {
    "allParticipants": "모든 구성원",
    "searchHint": "주소 또는 장소 검색",
    "noSearchResults": "일치하는 위치를 찾지 못했습니다.",
    "searchFailed": "위치를 검색할 수 없습니다. 다시 시도하세요.",
    "savedPermissionRequired": "설정이 저장되었습니다. 이 기기에는 아직 위치 권한을 ‘항상 허용’으로 설정해야 합니다.",
  },
  "ja": {
    "allParticipants": "すべてのメンバー",
    "searchHint": "住所または場所を検索",
    "noSearchResults": "一致する場所が見つかりませんでした。",
    "searchFailed": "場所を検索できません。もう一度お試しください。",
    "savedPermissionRequired": "設定を保存しました。この端末では位置情報を「常に許可」にする必要があります。",
  },
  "de": {
    "allParticipants": "Alle Mitglieder",
    "searchHint": "Adresse oder Ort suchen",
    "noSearchResults": "Kein passender Ort gefunden.",
    "searchFailed": "Der Ort konnte nicht gesucht werden. Versuche es erneut.",
    "savedPermissionRequired": "Einstellungen gespeichert. Dieses Gerät benötigt weiterhin den Standortzugriff „Immer“.",
  },
  "ru": {
    "allParticipants": "Все участники",
    "searchHint": "Поиск адреса или места",
    "noSearchResults": "Подходящее место не найдено.",
    "searchFailed": "Не удалось выполнить поиск места. Повторите попытку.",
    "savedPermissionRequired": "Настройки сохранены. На этом устройстве всё ещё нужно разрешить доступ к геопозиции «Всегда».",
  },
  "fr": {
    "allParticipants": "Tous les membres",
    "searchHint": "Rechercher une adresse ou un lieu",
    "noSearchResults": "Aucun lieu correspondant n’a été trouvé.",
    "searchFailed": "Impossible de rechercher un lieu. Réessayez.",
    "savedPermissionRequired": "Paramètres enregistrés. Cet appareil nécessite toujours l’autorisation de localisation « Toujours ».",
  },
  "es": {
    "allParticipants": "Todos los miembros",
    "searchHint": "Buscar una dirección o un lugar",
    "noSearchResults": "No se encontró ninguna ubicación coincidente.",
    "searchFailed": "No se pudo buscar la ubicación. Inténtalo de nuevo.",
    "savedPermissionRequired": "Configuración guardada. Este dispositivo aún necesita el permiso de ubicación «Siempre».",
  },
  "id": {
    "allParticipants": "Semua anggota",
    "searchHint": "Cari alamat atau tempat",
    "noSearchResults": "Lokasi yang cocok tidak ditemukan.",
    "searchFailed": "Tidak dapat mencari lokasi. Coba lagi.",
    "savedPermissionRequired": "Pengaturan disimpan. Perangkat ini masih memerlukan izin lokasi Selalu.",
  },
  "th": {
    "allParticipants": "สมาชิกทั้งหมด",
    "searchHint": "ค้นหาที่อยู่หรือสถานที่",
    "noSearchResults": "ไม่พบตำแหน่งที่ตรงกัน",
    "searchFailed": "ไม่สามารถค้นหาตำแหน่งได้ โปรดลองอีกครั้ง",
    "savedPermissionRequired": "บันทึกการตั้งค่าแล้ว อุปกรณ์นี้ยังต้องได้รับสิทธิ์ตำแหน่งแบบอนุญาตตลอดเวลา",
  },
  "ms": {
    "allParticipants": "Semua ahli",
    "searchHint": "Cari alamat atau tempat",
    "noSearchResults": "Tiada lokasi yang sepadan ditemui.",
    "searchFailed": "Lokasi tidak dapat dicari. Cuba lagi.",
    "savedPermissionRequired": "Tetapan disimpan. Peranti ini masih memerlukan kebenaran lokasi Sentiasa.",
  },
  "fil": {
    "allParticipants": "Lahat ng miyembro",
    "searchHint": "Maghanap ng address o lugar",
    "noSearchResults": "Walang nakitang tugmang lokasyon.",
    "searchFailed": "Hindi mahanap ang lokasyon. Subukan muli.",
    "savedPermissionRequired": "Na-save ang mga setting. Kailangan pa rin ng device na ito ang pahintulot sa lokasyon na Palagi.",
  },
  "km": {
    "allParticipants": "សមាជិកទាំងអស់",
    "searchHint": "ស្វែងរកអាសយដ្ឋាន ឬទីកន្លែង",
    "noSearchResults": "រកមិនឃើញទីតាំងដែលត្រូវគ្នាទេ។",
    "searchFailed": "មិនអាចស្វែងរកទីតាំងបានទេ។ សូមព្យាយាមម្តងទៀត។",
    "savedPermissionRequired": "បានរក្សាទុកការកំណត់។ ឧបករណ៍នេះនៅតែត្រូវការសិទ្ធិទីតាំង «ជានិច្ច»។",
  },
  "my": {
    "allParticipants": "အဖွဲ့ဝင်အားလုံး",
    "searchHint": "လိပ်စာ သို့မဟုတ် နေရာကို ရှာရန်",
    "noSearchResults": "ကိုက်ညီသော နေရာ မတွေ့ပါ။",
    "searchFailed": "နေရာကို ရှာမရပါ။ ထပ်မံကြိုးစားပါ။",
    "savedPermissionRequired": "ဆက်တင်များကို သိမ်းပြီးပါပြီ။ ဤစက်တွင် တည်နေရာခွင့်ပြုချက်ကို အမြဲတမ်း ခွင့်ပြုရန် လိုအပ်နေဆဲဖြစ်သည်။",
  },
  "lo": {
    "allParticipants": "ສະມາຊິກທັງໝົດ",
    "searchHint": "ຄົ້ນຫາທີ່ຢູ່ ຫຼື ສະຖານທີ່",
    "noSearchResults": "ບໍ່ພົບສະຖານທີ່ທີ່ກົງກັນ.",
    "searchFailed": "ບໍ່ສາມາດຄົ້ນຫາສະຖານທີ່ໄດ້. ລອງໃໝ່.",
    "savedPermissionRequired": "ບັນທຶກການຕັ້ງຄ່າແລ້ວ. ອຸປະກອນນີ້ຍັງຕ້ອງການສິດຕຳແໜ່ງແບບ ອະນຸຍາດສະເໝີ.",
  },
  "ta": {
    "allParticipants": "அனைத்து உறுப்பினர்களும்",
    "searchHint": "முகவரி அல்லது இடத்தைத் தேடுங்கள்",
    "noSearchResults": "பொருந்தும் இடம் எதுவும் கிடைக்கவில்லை.",
    "searchFailed": "இடத்தைத் தேட முடியவில்லை. மீண்டும் முயற்சிக்கவும்.",
    "savedPermissionRequired": "அமைப்புகள் சேமிக்கப்பட்டன. இந்தச் சாதனத்திற்கு இன்னும் எப்போதும் இருப்பிட அனுமதி தேவை.",
  },
  "pt": {
    "allParticipants": "Todos os membros",
    "searchHint": "Pesquisar um endereço ou local",
    "noSearchResults": "Nenhum local correspondente foi encontrado.",
    "searchFailed": "Não foi possível pesquisar o local. Tente novamente.",
    "savedPermissionRequired": "Definições guardadas. Este dispositivo ainda precisa da permissão de localização «Sempre».",
  },
  "tet": {
    "allParticipants": "Membru hotu",
    "searchHint": "Buka enderesu ka fatin",
    "noSearchResults": "La hetan fatin ne'ebé corresponde.",
    "searchFailed": "La bele buka fatin. Kokor fali.",
    "savedPermissionRequired": "Konfigurasaun rai ona. Dispozitivu ne'e sei presiza permisaun lokalizasaun Sempre.",
  },
  "it": {
    "allParticipants": "Tutti i membri",
    "searchHint": "Cerca un indirizzo o un luogo",
    "noSearchResults": "Nessuna posizione corrispondente trovata.",
    "searchFailed": "Impossibile cercare la posizione. Riprova.",
    "savedPermissionRequired": "Impostazioni salvate. Questo dispositivo necessita ancora dell’autorizzazione alla posizione «Sempre».",
  },
  "pl": {
    "allParticipants": "Wszyscy członkowie",
    "searchHint": "Wyszukaj adres lub miejsce",
    "noSearchResults": "Nie znaleziono pasującej lokalizacji.",
    "searchFailed": "Nie można wyszukać lokalizacji. Spróbuj ponownie.",
    "savedPermissionRequired": "Ustawienia zapisano. To urządzenie nadal wymaga dostępu do lokalizacji „Zawsze”.",
  },
  "nl": {
    "allParticipants": "Alle leden",
    "searchHint": "Zoek een adres of plaats",
    "noSearchResults": "Geen overeenkomende locatie gevonden.",
    "searchFailed": "Kan de locatie niet zoeken. Probeer het opnieuw.",
    "savedPermissionRequired": "Instellingen opgeslagen. Dit apparaat heeft nog steeds locatietoegang ‘Altijd’ nodig.",
  },
  "cs": {
    "allParticipants": "Všichni členové",
    "searchHint": "Vyhledat adres nebo místo",
    "noSearchResults": "Nebyla nalezena žádná odpovídající poloha.",
    "searchFailed": "Polohu nelze vyhledat. Zkuste to znovu.",
    "savedPermissionRequired": "Nastavení bylo uloženo. Toto zařízení stále potřebuje oprávnění k poloze „Vždy“.",
  },
  "sk": {
    "allParticipants": "Všetci členovia",
    "searchHint": "Vyhľadať adresu alebo miesto",
    "noSearchResults": "Nenašla sa žiadna zodpovedajúca poloha.",
    "searchFailed": "Polohu sa nepodarilo vyhľadať. Skúste to znova.",
    "savedPermissionRequired": "Nastavenia boli uložené. Toto zariadenie stále potrebuje povolenie polohy „Vždy“.",
  },
  "uk": {
    "allParticipants": "Усі учасники",
    "searchHint": "Пошук адреси або місця",
    "noSearchResults": "Відповідне місце не знайдено.",
    "searchFailed": "Не вдалося знайти місце. Спробуйте ще раз.",
    "savedPermissionRequired": "Налаштування збережено. На цьому пристрої все ще потрібно надати доступ до геопозиції «Завжди».",
  },
  "ro": {
    "allParticipants": "Toți membrii",
    "searchHint": "Caută o adresă sau un loc",
    "noSearchResults": "Nu a fost găsită nicio locație potrivită.",
    "searchFailed": "Locația nu a putut fi căutată. Încearcă din nou.",
    "savedPermissionRequired": "Setările au fost salvate. Acest dispozitiv încă necesită permisiunea de localizare „Întotdeauna”.",
  },
  "hu": {
    "allParticipants": "Minden tag",
    "searchHint": "Cím vagy hely keresése",
    "noSearchResults": "Nem található megfelelő hely.",
    "searchFailed": "A hely nem kereshető. Próbáld újra.",
    "savedPermissionRequired": "A beállítások mentve. Ezen az eszközön továbbra is szükséges a „Mindig” helyengedély.",
  },
  "bg": {
    "allParticipants": "Всички членове",
    "searchHint": "Търсене на адрес или място",
    "noSearchResults": "Не е намерено съответстващо местоположение.",
    "searchFailed": "Местоположението не може да бъде потърсено. Опитайте отново.",
    "savedPermissionRequired": "Настройките са запазени. Това устройство все още се нуждае от разрешение за местоположение „Винаги“.",
  },
  "hr": {
    "allParticipants": "Svi članovi",
    "searchHint": "Pretraži adresu ili mjesto",
    "noSearchResults": "Nije pronađena odgovarajuća lokacija.",
    "searchFailed": "Lokaciju nije moguće pretražiti. Pokušajte ponovno.",
    "savedPermissionRequired": "Postavke su spremljene. Ovaj uređaj još uvijek treba dopuštenje za lokaciju „Uvijek“.",
  },
  "sr": {
    "allParticipants": "Сви чланови",
    "searchHint": "Претражи адресу или место",
    "noSearchResults": "Није пронађена одговарајућа локација.",
    "searchFailed": "Локацију није могуће претражити. Покушајте поново.",
    "savedPermissionRequired": "Подешавања су сачувана. Овом уређају је и даље потребна дозвола за локацију „Увек“.",
  },
  "bs": {
    "allParticipants": "Svi članovi",
    "searchHint": "Pretraži adresu ili mjesto",
    "noSearchResults": "Nije pronađena odgovarajuća lokacija.",
    "searchFailed": "Lokaciju nije moguće pretražiti. Pokušajte ponovo.",
    "savedPermissionRequired": "Postavke su sačuvane. Ovom uređaju je i dalje potrebna dozvola za lokaciju „Uvijek“.",
  },
  "sl": {
    "allParticipants": "Vsi člani",
    "searchHint": "Poišči naslov ali kraj",
    "noSearchResults": "Ujemajoča se lokacija ni bila najdena.",
    "searchFailed": "Lokacije ni mogoče poiskati. Poskusite znova.",
    "savedPermissionRequired": "Nastavitve so shranjene. Ta naprava še vedno potrebuje dovoljenje za lokacijo »Vedno«.",
  },
  "mk": {
    "allParticipants": "Сите членови",
    "searchHint": "Пребарај адреса или место",
    "noSearchResults": "Не е пронајдена соодветна локација.",
    "searchFailed": "Локацијата не може да се пребара. Обидете се повторно.",
    "savedPermissionRequired": "Поставките се зачувани. На овој уред сè уште му е потребна дозвола за локација „Секогаш“.",
  },
  "sq": {
    "allParticipants": "Të gjithë anëtarët",
    "searchHint": "Kërko një adresë ose vend",
    "noSearchResults": "Nuk u gjet asnjë vendndodhje që përputhet.",
    "searchFailed": "Vendndodhja nuk mund të kërkohet. Provo përsëri.",
    "savedPermissionRequired": "Cilësimet u ruajtën. Kjo pajisje ka ende nevojë për lejen e vendndodhjes “Gjithmonë”.",
  },
  "el": {
    "allParticipants": "Όλα τα μέλη",
    "searchHint": "Αναζήτηση διεύθυνσης ή μέρους",
    "noSearchResults": "Δεν βρέθηκε τοποθεσία που να ταιριάζει.",
    "searchFailed": "Δεν είναι δυνατή η αναζήτηση τοποθεσίας. Δοκιμάστε ξανά.",
    "savedPermissionRequired": "Οι ρυθμίσεις αποθηκεύτηκαν. Αυτή η συσκευή εξακολουθεί να χρειάζεται άδεια τοποθεσίας «Πάντα».",
  },
  "tr": {
    "allParticipants": "Tüm üyeler",
    "searchHint": "Adres veya yer ara",
    "noSearchResults": "Eşleşen bir konum bulunamadı.",
    "searchFailed": "Konum aranamadı. Tekrar deneyin.",
    "savedPermissionRequired": "Ayarlar kaydedildi. Bu cihaz hâlâ Her Zaman konum iznine ihtiyaç duyuyor.",
  },
  "sv": {
    "allParticipants": "Alla medlemmar",
    "searchHint": "Sök efter en adress eller plats",
    "noSearchResults": "Ingen matchande plats hittades.",
    "searchFailed": "Det gick inte att söka efter platsen. Försök igen.",
    "savedPermissionRequired": "Inställningarna har sparats. Den här enheten behöver fortfarande platsbehörigheten Alltid.",
  },
  "da": {
    "allParticipants": "Alle medlemmer",
    "searchHint": "Søg efter en adresse eller et sted",
    "noSearchResults": "Der blev ikke fundet en matchende placering.",
    "searchFailed": "Placeringen kunne ikke søges. Prøv igen.",
    "savedPermissionRequired": "Indstillingerne er gemt. Denne enhed kræver stadig placeringstilladelsen Altid.",
  },
  "nb": {
    "allParticipants": "Alle medlemmer",
    "searchHint": "Søk etter en adresse eller et sted",
    "noSearchResults": "Fant ingen samsvarende plassering.",
    "searchFailed": "Kunne ikke søke etter plasseringen. Prøv igjen.",
    "savedPermissionRequired": "Innstillingene er lagret. Denne enheten trenger fortsatt posisjonstillatelsen Alltid.",
  },
  "fi": {
    "allParticipants": "Kaikki jäsenet",
    "searchHint": "Hae osoitetta tai paikkaa",
    "noSearchResults": "Vastaavaa sijaintia ei löytynyt.",
    "searchFailed": "Sijaintia ei voitu hakea. Yritä uudelleen.",
    "savedPermissionRequired": "Asetukset tallennettiin. Tämä laite tarvitsee edelleen sijaintiluvan Aina.",
  },
  "is": {
    "allParticipants": "Allir meðlimir",
    "searchHint": "Leita að heimilisfangi eða stað",
    "noSearchResults": "Engin samsvarandi staðsetning fannst.",
    "searchFailed": "Ekki tókst að leita að staðsetningu. Reyndu aftur.",
    "savedPermissionRequired": "Stillingar vistaðar. Þetta tæki þarf enn staðsetningarheimildina Alltaf.",
  },
  "et": {
    "allParticipants": "Kõik liikmed",
    "searchHint": "Otsi aadressi või kohta",
    "noSearchResults": "Sobivat asukohta ei leitud.",
    "searchFailed": "Asukohta ei saanud otsida. Proovi uuesti.",
    "savedPermissionRequired": "Seaded salvestati. See seade vajab endiselt asukohaluba „Alati“.",
  },
  "lv": {
    "allParticipants": "Visi dalībnieki",
    "searchHint": "Meklēt adresi vai vietu",
    "noSearchResults": "Atbilstoša atrašanās vieta netika atrasta.",
    "searchFailed": "Atrašanās vietu neizdevās meklēt. Mēģiniet vēlreiz.",
    "savedPermissionRequired": "Iestatījumi saglabāti. Šai ierīcei joprojām nepieciešama atrašanās vietas atļauja “Vienmēr”.",
  },
  "lt": {
    "allParticipants": "Visi nariai",
    "searchHint": "Ieškoti adreso arba vietos",
    "noSearchResults": "Atitinkama vieta nerasta.",
    "searchFailed": "Vietos nepavyko ieškoti. Bandykite dar kartą.",
    "savedPermissionRequired": "Nustatymai išsaugoti. Šiam įrenginiui vis dar reikia vietos leidimo „Visada“.",
  },
  "ga": {
    "allParticipants": "Gach ball",
    "searchHint": "Cuardaigh seoladh nó áit",
    "noSearchResults": "Níor aimsíodh suíomh a mheaitseálann.",
    "searchFailed": "Níorbh fhéidir an suíomh a chuardach. Bain triail eile as.",
    "savedPermissionRequired": "Sábháladh na socruithe. Teastaíonn cead suímh I gCónaí ón ngléas seo fós.",
  },
  "mt": {
    "allParticipants": "Il-membri kollha",
    "searchHint": "Fittex indirizz jew post",
    "noSearchResults": "Ma nstab l-ebda post li jaqbel.",
    "searchFailed": "Ma setax jitfittex il-post. Erġa’ pprova.",
    "savedPermissionRequired": "Is-settings ġew salvati. Dan l-apparat għadu jeħtieġ il-permess tal-post Dejjem.",
  },
  "be": {
    "allParticipants": "Усе ўдзельнікі",
    "searchHint": "Пошук адраса або месца",
    "noSearchResults": "Адпаведнае месца не знойдзена.",
    "searchFailed": "Не ўдалося знайсці месца. Паспрабуйце яшчэ раз.",
    "savedPermissionRequired": "Налады захаваны. На гэтай прыладзе ўсё яшчэ патрэбны дазвол на месцазнаходжанне «Заўсёды».",
  },
  "lb": {
    "allParticipants": "All Memberen",
    "searchHint": "Adress oder Plaz sichen",
    "noSearchResults": "Keng passend Plaz fonnt.",
    "searchFailed": "D’Plaz konnt net gesicht ginn. Probéiert nach eng Kéier.",
    "savedPermissionRequired": "D’Astellunge goufe gespäichert. Dësen Apparat brauch nach ëmmer d’Standuertberechtegung Ëmmer.",
  },
  "ca": {
    "allParticipants": "Tots els membres",
    "searchHint": "Cercar una adreça o un lloc",
    "noSearchResults": "No s’ha trobat cap ubicació coincident.",
    "searchFailed": "No s’ha pogut cercar la ubicació. Torna-ho a provar.",
    "savedPermissionRequired": "S’han desat els paràmetres. Aquest dispositiu encara necessita el permís d’ubicació «Sempre».",
  },
  "cnr": {
    "allParticipants": "Svi članovi",
    "searchHint": "Pretraži adresu ili mjesto",
    "noSearchResults": "Nije pronađena odgovarajuća lokacija.",
    "searchFailed": "Lokaciju nije moguće pretražiti. Pokušajte ponovo.",
    "savedPermissionRequired": "Podešavanja su sačuvana. Ovom uređaju je i dalje potrebna dozvola za lokaciju „Uvijek“.",
  },
  "hy": {
    "allParticipants": "Բոլոր անդամները",
    "searchHint": "Փնտրել հասցե կամ վայր",
    "noSearchResults": "Համապատասխան տեղադրություն չի գտնվել։",
    "searchFailed": "Չհաջողվեց որոնել տեղադրությունը։ Փորձեք կրկին։",
    "savedPermissionRequired": "Կարգավորումները պահպանվել են։ Այս սարքին դեռ անհրաժեշտ է տեղադրության «Միշտ» թույլտվություն։",
  },
  "ka": {
    "allParticipants": "ყველა წევრი",
    "searchHint": "მისამართის ან ადგილის ძიება",
    "noSearchResults": "შესაბამისი მდებარეობა ვერ მოიძებნა.",
    "searchFailed": "მდებარეობის მოძიება ვერ მოხერხდა. სცადეთ ხელახლა.",
    "savedPermissionRequired": "პარამეტრები შენახულია. ამ მოწყობილობას კვლავ სჭირდება მდებარეობის ნებართვა „ყოველთვის“.",
  },
  "az": {
    "allParticipants": "Bütün üzvlər",
    "searchHint": "Ünvan və ya məkan axtar",
    "noSearchResults": "Uyğun məkan tapılmadı.",
    "searchFailed": "Məkanı axtarmaq mümkün olmadı. Yenidən cəhd edin.",
    "savedPermissionRequired": "Ayarlar yadda saxlanıldı. Bu cihazda məkan icazəsi hələ də Həmişə olaraq verilməlidir.",
  },
};

extension AutoAwayFeatureStrings on AppStrings {
  String get _autoAwayLanguageCode {
    if (isEnglish) return "en";
    if (isChinese) return "zh";
    if (isKorean) return "ko";
    if (isJapanese) return "ja";
    if (isGerman) return "de";
    if (isRussian) return "ru";
    if (isFrench) return "fr";
    if (isSpanish) return "es";
    if (isIndonesian) return "id";
    if (isThai) return "th";
    if (isMalay) return "ms";
    if (isFilipino) return "fil";
    if (isKhmer) return "km";
    if (isBurmese) return "my";
    if (isLao) return "lo";
    if (isTamil) return "ta";
    if (isPortuguese) return "pt";
    if (isTetum) return "tet";
    if (isItalian) return "it";
    if (isPolish) return "pl";
    if (isDutch) return "nl";
    if (isCzech) return "cs";
    if (isSlovak) return "sk";
    if (isUkrainian) return "uk";
    if (isRomanian) return "ro";
    if (isHungarian) return "hu";
    if (isBulgarian) return "bg";
    if (isCroatian) return "hr";
    if (isSerbian) return "sr";
    if (isBosnian) return "bs";
    if (isSlovenian) return "sl";
    if (isMacedonian) return "mk";
    if (isAlbanian) return "sq";
    if (isGreek) return "el";
    if (isTurkish) return "tr";
    if (isSwedish) return "sv";
    if (isDanish) return "da";
    if (isNorwegianBokmal) return "nb";
    if (isFinnish) return "fi";
    if (isIcelandic) return "is";
    if (isEstonian) return "et";
    if (isLatvian) return "lv";
    if (isLithuanian) return "lt";
    if (isIrish) return "ga";
    if (isMaltese) return "mt";
    if (isBelarusian) return "be";
    if (isLuxembourgish) return "lb";
    if (isCatalan) return "ca";
    if (isMontenegrin) return "cnr";
    if (isArmenian) return "hy";
    if (isGeorgian) return "ka";
    if (isAzerbaijani) return "az";
    return "vi";
  }

  String _autoAwayFeatureText(String key) {
    final localeValues = _autoAwayFeatureTranslations[_autoAwayLanguageCode];
    final value = localeValues?[key];

    assert(value != null && value.isNotEmpty, "Missing Auto Away translation: $_autoAwayLanguageCode/$key");
    return value ?? _autoAwayFeatureTranslations["en"]![key]!;
  }

  String _autoAwayControlText(String key) {
    final localeValues = _autoAwayControlTranslations[_autoAwayLanguageCode];
    final value = localeValues?[key];

    assert(value != null && value.isNotEmpty, "Missing Auto Away control translation: $_autoAwayLanguageCode/$key");
    return value ?? _autoAwayControlTranslations["en"]![key]!;
  }

  String get autoAwayChooseOnMap => _autoAwayFeatureText("chooseOnMap");
  String get autoAwayParticipantsTitle => _autoAwayFeatureText("participantsTitle");
  String get autoAwayStatusParticipantsCount =>
      _autoAwayFeatureText("statusParticipantsCount");
  String get autoAwayParticipantsDescription => _autoAwayFeatureText("participantsDescription");
  String get autoAwaySelectAtLeastOneParticipant => _autoAwayFeatureText("selectAtLeastOneParticipant");
  String get autoAwayMapTitle => _autoAwayFeatureText("mapTitle");
  String get autoAwayMapHint => _autoAwayFeatureText("mapHint");
  String get autoAwayConfirmMapLocation => _autoAwayFeatureText("confirmMapLocation");
  String get autoAwayEnabledForSelectedParticipants => _autoAwayFeatureText("enabledForSelectedParticipants");
  String get autoAwaySelectedMembersPermissionHint => _autoAwayFeatureText("selectedMembersPermissionHint");
  String get autoAwayAllParticipants => _autoAwayControlText("allParticipants");
  String get autoAwaySearchHint => _autoAwayControlText("searchHint");
  String get autoAwayNoSearchResults => _autoAwayControlText("noSearchResults");
  String get autoAwaySearchFailed => _autoAwayControlText("searchFailed");
  String get autoAwaySavedPermissionRequired => _autoAwayControlText("savedPermissionRequired");
}
