import 'app_strings.dart';

extension HubUpdateStrings on AppStrings {
  static const int _expectedHubUpdateStringCount = 18;

  List<String> get _hubUpdateBundle {
    final values = choose(
      vi: "Cập nhật Hub\u001fHub đang ở phiên bản mới nhất.\u001fPhiên bản {release} đã sẵn sàng.\u001fĐã gửi yêu cầu, đang chờ Hub tiếp nhận.\u001fHub đang chuẩn bị và cài đặt bản cập nhật.\u001fCập nhật Hub thành công.\u001fCập nhật Hub thất bại.\u001fYêu cầu cập nhật đã bị từ chối.\u001fDịch vụ cập nhật của Hub chưa sẵn sàng.\u001fHub đang offline. Hãy chờ Hub online trước khi cập nhật.\u001fChỉ Chủ nhà mới có thể bắt đầu cập nhật.\u001fBản cập nhật quan trọng\u001fCập nhật ngay\u001fThử lại\u001fXác nhận cập nhật Hub\u001fCập nhật Hub lên {release}? Hub có thể tạm thời mất kết nối. Không ngắt nguồn trong quá trình cập nhật.\u001fĐã gửi yêu cầu cập nhật đến Hub.\u001fKhông thể gửi yêu cầu cập nhật.",
      en: "Hub update\u001fThe Hub is up to date.\u001fVersion {release} is ready.\u001fRequest sent. Waiting for the Hub to receive it.\u001fThe Hub is preparing and installing the update.\u001fHub update completed successfully.\u001fHub update failed.\u001fThe update request was rejected.\u001fThe Hub update service is not ready.\u001fThe Hub is offline. Wait until it is online before updating.\u001fOnly the Home Owner can start an update.\u001fCritical update\u001fUpdate now\u001fTry again\u001fConfirm Hub update\u001fUpdate the Hub to {release}? The Hub may temporarily disconnect. Do not unplug it during the update.\u001fThe update request was sent to the Hub.\u001fUnable to send the update request.",
      zh: "Hub 更新\u001fHub 已是最新版本。\u001f版本 {release} 已可用。\u001f请求已发送，正在等待 Hub 接收。\u001fHub 正在准备并安装更新。\u001fHub 更新成功。\u001fHub 更新失败。\u001f更新请求已被拒绝。\u001fHub 更新服务尚未就绪。\u001fHub 当前离线，请等待其上线后再更新。\u001f只有房屋所有者可以开始更新。\u001f重要更新\u001f立即更新\u001f重试\u001f确认更新 Hub\u001f将 Hub 更新到 {release}？更新期间 Hub 可能暂时断开连接，请勿断电。\u001f更新请求已发送到 Hub。\u001f无法发送更新请求。",
      ko: "Hub 업데이트\u001fHub가 최신 버전입니다.\u001f버전 {release}을 사용할 수 있습니다.\u001f요청을 보냈습니다. Hub가 수신하기를 기다리는 중입니다.\u001fHub가 업데이트를 준비하고 설치하는 중입니다.\u001fHub 업데이트가 완료되었습니다.\u001fHub 업데이트에 실패했습니다.\u001f업데이트 요청이 거부되었습니다.\u001fHub 업데이트 서비스가 준비되지 않았습니다.\u001fHub가 오프라인입니다. 온라인이 된 후 업데이트하세요.\u001f집 소유자만 업데이트를 시작할 수 있습니다.\u001f중요 업데이트\u001f지금 업데이트\u001f다시 시도\u001fHub 업데이트 확인\u001fHub를 {release}(으)로 업데이트할까요? 업데이트 중 일시적으로 연결이 끊길 수 있으니 전원을 분리하지 마세요.\u001f업데이트 요청을 Hub로 보냈습니다.\u001f업데이트 요청을 보낼 수 없습니다.",
      ja: "Hubの更新\u001fHubは最新です。\u001fバージョン{release}を利用できます。\u001fリクエストを送信しました。Hubの受信を待っています。\u001fHubが更新を準備してインストールしています。\u001fHubの更新が完了しました。\u001fHubの更新に失敗しました。\u001f更新リクエストが拒否されました。\u001fHubの更新サービスはまだ準備できていません。\u001fHubはオフラインです。オンラインになってから更新してください。\u001f更新を開始できるのは家のオーナーだけです。\u001f重要な更新\u001f今すぐ更新\u001f再試行\u001fHubの更新を確認\u001fHubを{release}に更新しますか？更新中は一時的に接続が切れることがあります。電源を抜かないでください。\u001f更新リクエストをHubに送信しました。\u001f更新リクエストを送信できません。",
      de: "Hub-Update\u001fDer Hub ist auf dem neuesten Stand.\u001fVersion {release} ist verfügbar.\u001fAnfrage gesendet. Der Hub wird benachrichtigt.\u001fDer Hub bereitet das Update vor und installiert es.\u001fHub-Update erfolgreich abgeschlossen.\u001fHub-Update fehlgeschlagen.\u001fDie Update-Anfrage wurde abgelehnt.\u001fDer Update-Dienst des Hubs ist noch nicht bereit.\u001fDer Hub ist offline. Warten Sie, bis er online ist.\u001fNur der Hauseigentümer kann ein Update starten.\u001fKritisches Update\u001fJetzt aktualisieren\u001fErneut versuchen\u001fHub-Update bestätigen\u001fHub auf {release} aktualisieren? Die Verbindung kann vorübergehend unterbrochen werden. Trennen Sie während des Updates nicht die Stromversorgung.\u001fDie Update-Anfrage wurde an den Hub gesendet.\u001fDie Update-Anfrage konnte nicht gesendet werden.",
      ru: "Обновление Hub\u001fНа Hub установлена последняя версия.\u001fДоступна версия {release}.\u001fЗапрос отправлен. Ожидание получения Hub.\u001fHub подготавливает и устанавливает обновление.\u001fОбновление Hub успешно завершено.\u001fНе удалось обновить Hub.\u001fЗапрос на обновление отклонён.\u001fСлужба обновления Hub ещё не готова.\u001fHub не в сети. Дождитесь подключения перед обновлением.\u001fТолько владелец дома может запустить обновление.\u001fКритическое обновление\u001fОбновить сейчас\u001fПовторить\u001fПодтвердите обновление Hub\u001fОбновить Hub до {release}? Hub может временно отключиться. Не выключайте питание во время обновления.\u001fЗапрос на обновление отправлен на Hub.\u001fНе удалось отправить запрос на обновление.",
      fr: "Mise à jour du Hub\u001fLe Hub est à jour.\u001fLa version {release} est disponible.\u001fDemande envoyée. En attente de réception par le Hub.\u001fLe Hub prépare et installe la mise à jour.\u001fMise à jour du Hub réussie.\u001fÉchec de la mise à jour du Hub.\u001fLa demande de mise à jour a été refusée.\u001fLe service de mise à jour du Hub n’est pas prêt.\u001fLe Hub est hors ligne. Attendez qu’il soit en ligne avant la mise à jour.\u001fSeul le propriétaire du domicile peut lancer une mise à jour.\u001fMise à jour critique\u001fMettre à jour\u001fRéessayer\u001fConfirmer la mise à jour du Hub\u001fMettre le Hub à jour vers {release} ? Il peut être temporairement déconnecté. Ne coupez pas son alimentation pendant la mise à jour.\u001fLa demande de mise à jour a été envoyée au Hub.\u001fImpossible d’envoyer la demande de mise à jour.",
      es: "Actualización del Hub\u001fEl Hub está actualizado.\u001fLa versión {release} está disponible.\u001fSolicitud enviada. Esperando a que el Hub la reciba.\u001fEl Hub está preparando e instalando la actualización.\u001fLa actualización del Hub se completó correctamente.\u001fLa actualización del Hub falló.\u001fLa solicitud de actualización fue rechazada.\u001fEl servicio de actualización del Hub no está listo.\u001fEl Hub está sin conexión. Espera a que esté en línea antes de actualizar.\u001fSolo el propietario de la casa puede iniciar una actualización.\u001fActualización crítica\u001fActualizar ahora\u001fReintentar\u001fConfirmar actualización del Hub\u001f¿Actualizar el Hub a {release}? Puede desconectarse temporalmente. No lo desenchufes durante la actualización.\u001fLa solicitud de actualización se envió al Hub.\u001fNo se pudo enviar la solicitud de actualización.",
      id: "Pembaruan Hub\u001fHub sudah menggunakan versi terbaru.\u001fVersi {release} tersedia.\u001fPermintaan dikirim. Menunggu Hub menerimanya.\u001fHub sedang menyiapkan dan memasang pembaruan.\u001fPembaruan Hub berhasil.\u001fPembaruan Hub gagal.\u001fPermintaan pembaruan ditolak.\u001fLayanan pembaruan Hub belum siap.\u001fHub sedang offline. Tunggu hingga online sebelum memperbarui.\u001fHanya Pemilik Rumah yang dapat memulai pembaruan.\u001fPembaruan penting\u001fPerbarui sekarang\u001fCoba lagi\u001fKonfirmasi pembaruan Hub\u001fPerbarui Hub ke {release}? Hub mungkin terputus sementara. Jangan cabut daya selama pembaruan.\u001fPermintaan pembaruan telah dikirim ke Hub.\u001fTidak dapat mengirim permintaan pembaruan.",
      th: "อัปเดต Hub\u001fHub เป็นเวอร์ชันล่าสุดแล้ว\u001fเวอร์ชัน {release} พร้อมใช้งานแล้ว\u001fส่งคำขอแล้ว กำลังรอ Hub รับคำขอ\u001fHub กำลังเตรียมและติดตั้งการอัปเดต\u001fอัปเดต Hub สำเร็จ\u001fอัปเดต Hub ไม่สำเร็จ\u001fคำขออัปเดตถูกปฏิเสธ\u001fบริการอัปเดตของ Hub ยังไม่พร้อม\u001fHub ออฟไลน์ โปรดรอให้กลับมาออนไลน์ก่อนอัปเดต\u001fเฉพาะเจ้าของบ้านเท่านั้นที่เริ่มการอัปเดตได้\u001fการอัปเดตสำคัญ\u001fอัปเดตตอนนี้\u001fลองอีกครั้ง\u001fยืนยันการอัปเดต Hub\u001fอัปเดต Hub เป็น {release} หรือไม่? Hub อาจตัดการเชื่อมต่อชั่วคราว ห้ามถอดปลั๊กระหว่างการอัปเดต\u001fส่งคำขออัปเดตไปยัง Hub แล้ว\u001fไม่สามารถส่งคำขออัปเดตได้",
      ms: "Kemas kini Hub\u001fHub sudah menggunakan versi terkini.\u001fVersi {release} tersedia.\u001fPermintaan dihantar. Menunggu Hub menerimanya.\u001fHub sedang menyediakan dan memasang kemas kini.\u001fKemas kini Hub berjaya.\u001fKemas kini Hub gagal.\u001fPermintaan kemas kini ditolak.\u001fPerkhidmatan kemas kini Hub belum bersedia.\u001fHub di luar talian. Tunggu sehingga ia dalam talian sebelum mengemas kini.\u001fHanya Pemilik Rumah boleh memulakan kemas kini.\u001fKemas kini kritikal\u001fKemas kini sekarang\u001fCuba lagi\u001fSahkan kemas kini Hub\u001fKemas kini Hub kepada {release}? Hub mungkin terputus buat sementara waktu. Jangan cabut kuasa semasa kemas kini.\u001fPermintaan kemas kini telah dihantar ke Hub.\u001fTidak dapat menghantar permintaan kemas kini.",
      fil: "Update ng Hub\u001fNasa pinakabagong bersyon na ang Hub.\u001fHanda na ang bersyong {release}.\u001fNaipadala ang kahilingan. Hinihintay na matanggap ito ng Hub.\u001fInihahanda at ini-install ng Hub ang update.\u001fMatagumpay ang update ng Hub.\u001fNabigo ang update ng Hub.\u001fTinanggihan ang kahilingan sa update.\u001fHindi pa handa ang serbisyo ng update ng Hub.\u001fOffline ang Hub. Hintaying mag-online bago mag-update.\u001fAng May-ari ng Bahay lamang ang maaaring magsimula ng update.\u001fMahalagang update\u001fI-update ngayon\u001fSubukan muli\u001fKumpirmahin ang update ng Hub\u001fI-update ang Hub sa {release}? Maaaring pansamantalang mawalan ng koneksyon. Huwag tanggalin sa saksakan habang nag-a-update.\u001fNaipadala sa Hub ang kahilingan sa update.\u001fHindi maipadala ang kahilingan sa update.",
      km: "អាប់ដេត Hub\u001fHub កំពុងប្រើកំណែថ្មីបំផុត។\u001fកំណែ {release} បានរួចរាល់។\u001fបានផ្ញើសំណើ កំពុងរង់ចាំ Hub ទទួល។\u001fHub កំពុងរៀបចំ និងដំឡើងអាប់ដេត។\u001fអាប់ដេត Hub បានជោគជ័យ។\u001fអាប់ដេត Hub បានបរាជ័យ។\u001fសំណើអាប់ដេតត្រូវបានបដិសេធ។\u001fសេវាអាប់ដេត Hub មិនទាន់រួចរាល់។\u001fHub កំពុងក្រៅបណ្តាញ។ សូមរង់ចាំឱ្យអនឡាញមុនអាប់ដេត។\u001fមានតែម្ចាស់ផ្ទះប៉ុណ្ណោះដែលអាចចាប់ផ្តើមអាប់ដេត។\u001fអាប់ដេតសំខាន់\u001fអាប់ដេតឥឡូវ\u001fព្យាយាមម្តងទៀត\u001fបញ្ជាក់ការអាប់ដេត Hub\u001fអាប់ដេត Hub ទៅ {release} ឬ? Hub អាចផ្តាច់ការតភ្ជាប់បណ្តោះអាសន្ន។ កុំផ្តាច់ភ្លើងពេលអាប់ដេត។\u001fបានផ្ញើសំណើអាប់ដេតទៅ Hub។\u001fមិនអាចផ្ញើសំណើអាប់ដេតបាន។",
      my: "Hub အပ်ဒိတ်\u001fHub သည် နောက်ဆုံးဗားရှင်းဖြစ်နေပါပြီ။\u001fဗားရှင်း {release} အသင့်ဖြစ်ပါပြီ။\u001fတောင်းဆိုချက်ပို့ပြီး Hub လက်ခံရန် စောင့်နေသည်။\u001fHub သည် အပ်ဒိတ်ကို ပြင်ဆင်ပြီး ထည့်သွင်းနေသည်။\u001fHub အပ်ဒိတ် အောင်မြင်ပါသည်။\u001fHub အပ်ဒိတ် မအောင်မြင်ပါ။\u001fအပ်ဒိတ်တောင်းဆိုချက်ကို ငြင်းပယ်ခဲ့သည်။\u001fHub အပ်ဒိတ်ဝန်ဆောင်မှု မအဆင်သင့်သေးပါ။\u001fHub အော့ဖ်လိုင်းဖြစ်နေသည်။ အွန်လိုင်းပြန်ဖြစ်မှ အပ်ဒိတ်လုပ်ပါ။\u001fအိမ်ပိုင်ရှင်သာ အပ်ဒိတ်ကို စတင်နိုင်သည်။\u001fအရေးကြီးအပ်ဒိတ်\u001fယခုအပ်ဒိတ်လုပ်ရန်\u001fထပ်ကြိုးစားရန်\u001fHub အပ်ဒိတ် အတည်ပြုရန်\u001fHub ကို {release} သို့ အပ်ဒိတ်လုပ်မလား? ခဏတာ ချိတ်ဆက်မှုပြတ်နိုင်သည်။ အပ်ဒိတ်အတွင်း မီးအားမဖြုတ်ပါနှင့်။\u001fအပ်ဒိတ်တောင်းဆိုချက်ကို Hub သို့ ပို့ပြီးပါပြီ။\u001fအပ်ဒိတ်တောင်းဆိုချက် မပို့နိုင်ပါ။",
      lo: "ອັບເດດ Hub\u001fHub ເປັນເວີຊັນລ່າສຸດແລ້ວ.\u001fເວີຊັນ {release} ພ້ອມໃຊ້ງານ.\u001fສົ່ງຄຳຂໍແລ້ວ ກຳລັງລໍຖ້າ Hub ຮັບ.\u001fHub ກຳລັງກຽມ ແລະຕິດຕັ້ງອັບເດດ.\u001fອັບເດດ Hub ສຳເລັດ.\u001fອັບເດດ Hub ບໍ່ສຳເລັດ.\u001fຄຳຂໍອັບເດດຖືກປະຕິເສດ.\u001fບໍລິການອັບເດດ Hub ຍັງບໍ່ພ້ອມ.\u001fHub ອອບລາຍ. ລໍຖ້າໃຫ້ອອນລາຍກ່ອນອັບເດດ.\u001fມີແຕ່ເຈົ້າຂອງເຮືອນເທົ່ານັ້ນທີ່ເລີ່ມອັບເດດໄດ້.\u001fອັບເດດສຳຄັນ\u001fອັບເດດດຽວນີ້\u001fລອງອີກຄັ້ງ\u001fຢືນຢັນການອັບເດດ Hub\u001fອັບເດດ Hub ເປັນ {release} ບໍ? Hub ອາດຂາດການເຊື່ອມຕໍ່ຊົ່ວຄາວ. ຢ່າຖອດໄຟລະຫວ່າງອັບເດດ.\u001fສົ່ງຄຳຂໍອັບເດດໄປ Hub ແລ້ວ.\u001fບໍ່ສາມາດສົ່ງຄຳຂໍອັບເດດໄດ້.",
      ta: "Hub புதுப்பிப்பு\u001fHub சமீபத்திய பதிப்பில் உள்ளது.\u001fபதிப்பு {release} தயாராக உள்ளது.\u001fகோரிக்கை அனுப்பப்பட்டது. Hub பெற காத்திருக்கிறது.\u001fHub புதுப்பிப்பைத் தயார் செய்து நிறுவுகிறது.\u001fHub புதுப்பிப்பு வெற்றிகரமாக முடிந்தது.\u001fHub புதுப்பிப்பு தோல்வியடைந்தது.\u001fபுதுப்பிப்பு கோரிக்கை நிராகரிக்கப்பட்டது.\u001fHub புதுப்பிப்பு சேவை இன்னும் தயாராக இல்லை.\u001fHub ஆஃப்லைனில் உள்ளது. ஆன்லைனில் வந்த பிறகு புதுப்பிக்கவும்.\u001fவீட்டு உரிமையாளர் மட்டுமே புதுப்பிப்பைத் தொடங்க முடியும்.\u001fமுக்கிய புதுப்பிப்பு\u001fஇப்போது புதுப்பிக்கவும்\u001fமீண்டும் முயற்சிக்கவும்\u001fHub புதுப்பிப்பை உறுதிப்படுத்தவும்\u001fHub-ஐ {release} க்கு புதுப்பிக்கவா? தற்காலிகமாக இணைப்பு துண்டிக்கப்படலாம். புதுப்பிக்கும் போது மின்சாரத்தை துண்டிக்க வேண்டாம்.\u001fபுதுப்பிப்பு கோரிக்கை Hub-க்கு அனுப்பப்பட்டது.\u001fபுதுப்பிப்பு கோரிக்கையை அனுப்ப முடியவில்லை.",
      pt: "Atualização do Hub\u001fO Hub está atualizado.\u001fA versão {release} está disponível.\u001fPedido enviado. A aguardar que o Hub o receba.\u001fO Hub está a preparar e instalar a atualização.\u001fAtualização do Hub concluída com sucesso.\u001fFalha na atualização do Hub.\u001fO pedido de atualização foi rejeitado.\u001fO serviço de atualização do Hub ainda não está pronto.\u001fO Hub está offline. Aguarde até ficar online antes de atualizar.\u001fApenas o proprietário da casa pode iniciar uma atualização.\u001fAtualização crítica\u001fAtualizar agora\u001fTentar novamente\u001fConfirmar atualização do Hub\u001fAtualizar o Hub para {release}? O Hub pode ficar temporariamente desconectado. Não desligue a alimentação durante a atualização.\u001fO pedido de atualização foi enviado ao Hub.\u001fNão foi possível enviar o pedido de atualização.",
      tet: "Atualiza Hub\u001fHub uza ona versaun foun liu.\u001fVersaun {release} prontu ona.\u001fHaruka ona pedidu. Hein Hub simu.\u001fHub prepara no instala hela atualizasaun.\u001fAtualizasaun Hub susesu.\u001fAtualizasaun Hub falla.\u001fPedidu atualizasaun rejeita ona.\u001fServisu atualizasaun Hub seidauk prontu.\u001fHub offline. Hein nia online molok atualiza.\u001fNa’in-uma deit bele hahú atualizasaun.\u001fAtualizasaun importante\u001fAtualiza agora\u001fKoko fali\u001fKonfirma atualizasaun Hub\u001fAtualiza Hub ba {release}? Hub bele deskonektadu temporáriu. Labele hasai eletrisidade durante atualizasaun.\u001fHaruka ona pedidu atualizasaun ba Hub.\u001fLabele haruka pedidu atualizasaun.",
      it: "Aggiornamento Hub\u001fL’Hub è aggiornato.\u001fLa versione {release} è disponibile.\u001fRichiesta inviata. In attesa che l’Hub la riceva.\u001fL’Hub sta preparando e installando l’aggiornamento.\u001fAggiornamento dell’Hub completato.\u001fAggiornamento dell’Hub non riuscito.\u001fLa richiesta di aggiornamento è stata rifiutata.\u001fIl servizio di aggiornamento dell’Hub non è pronto.\u001fL’Hub è offline. Attendi che torni online prima di aggiornare.\u001fSolo il proprietario della casa può avviare un aggiornamento.\u001fAggiornamento critico\u001fAggiorna ora\u001fRiprova\u001fConferma aggiornamento Hub\u001fAggiornare l’Hub a {release}? Potrebbe disconnettersi temporaneamente. Non scollegare l’alimentazione durante l’aggiornamento.\u001fLa richiesta di aggiornamento è stata inviata all’Hub.\u001fImpossibile inviare la richiesta di aggiornamento.",
      pl: "Aktualizacja Hub\u001fHub jest aktualny.\u001fWersja {release} jest dostępna.\u001fŻądanie wysłane. Oczekiwanie na odbiór przez Hub.\u001fHub przygotowuje i instaluje aktualizację.\u001fAktualizacja Hub zakończona pomyślnie.\u001fAktualizacja Hub nie powiodła się.\u001fŻądanie aktualizacji zostało odrzucone.\u001fUsługa aktualizacji Hub nie jest jeszcze gotowa.\u001fHub jest offline. Poczekaj, aż będzie online.\u001fTylko właściciel domu może rozpocząć aktualizację.\u001fAktualizacja krytyczna\u001fAktualizuj teraz\u001fSpróbuj ponownie\u001fPotwierdź aktualizację Hub\u001fZaktualizować Hub do {release}? Połączenie może zostać chwilowo przerwane. Nie odłączaj zasilania podczas aktualizacji.\u001fŻądanie aktualizacji zostało wysłane do Hub.\u001fNie można wysłać żądania aktualizacji.",
      nl: "Hub-update\u001fDe Hub is up-to-date.\u001fVersie {release} is beschikbaar.\u001fVerzoek verzonden. Wachten tot de Hub het ontvangt.\u001fDe Hub bereidt de update voor en installeert deze.\u001fHub-update succesvol voltooid.\u001fHub-update mislukt.\u001fHet updateverzoek is geweigerd.\u001fDe updateservice van de Hub is nog niet gereed.\u001fDe Hub is offline. Wacht tot hij online is voordat je bijwerkt.\u001fAlleen de huiseigenaar kan een update starten.\u001fKritieke update\u001fNu bijwerken\u001fOpnieuw proberen\u001fHub-update bevestigen\u001fDe Hub bijwerken naar {release}? De verbinding kan tijdelijk worden verbroken. Koppel de stroom niet los tijdens de update.\u001fHet updateverzoek is naar de Hub verzonden.\u001fHet updateverzoek kan niet worden verzonden.",
      cs: "Aktualizace Hubu\u001fHub je aktuální.\u001fVerze {release} je k dispozici.\u001fPožadavek byl odeslán. Čeká se na přijetí Hubem.\u001fHub připravuje a instaluje aktualizaci.\u001fAktualizace Hubu byla úspěšná.\u001fAktualizace Hubu selhala.\u001fPožadavek na aktualizaci byl odmítnut.\u001fSlužba aktualizace Hubu ještě není připravena.\u001fHub je offline. Před aktualizací počkejte, až bude online.\u001fAktualizaci může spustit pouze vlastník domu.\u001fKritická aktualizace\u001fAktualizovat nyní\u001fZkusit znovu\u001fPotvrdit aktualizaci Hubu\u001fAktualizovat Hub na {release}? Může se dočasně odpojit. Během aktualizace neodpojujte napájení.\u001fPožadavek na aktualizaci byl odeslán do Hubu.\u001fPožadavek na aktualizaci nelze odeslat.",
      sk: "Aktualizácia Hubu\u001fHub je aktuálny.\u001fVerzia {release} je k dispozícii.\u001fPožiadavka bola odoslaná. Čaká sa na prijatie Hubom.\u001fHub pripravuje a inštaluje aktualizáciu.\u001fAktualizácia Hubu bola úspešná.\u001fAktualizácia Hubu zlyhala.\u001fPožiadavka na aktualizáciu bola zamietnutá.\u001fSlužba aktualizácie Hubu ešte nie je pripravená.\u001fHub je offline. Pred aktualizáciou počkajte, kým bude online.\u001fAktualizáciu môže spustiť iba vlastník domu.\u001fKritická aktualizácia\u001fAktualizovať teraz\u001fSkúsiť znova\u001fPotvrdiť aktualizáciu Hubu\u001fAktualizovať Hub na {release}? Môže sa dočasne odpojiť. Počas aktualizácie neodpájajte napájanie.\u001fPožiadavka na aktualizáciu bola odoslaná do Hubu.\u001fPožiadavku na aktualizáciu nemožno odoslať.",
      uk: "Оновлення Hub\u001fНа Hub встановлено останню версію.\u001fДоступна версія {release}.\u001fЗапит надіслано. Очікування отримання Hub.\u001fHub готує та встановлює оновлення.\u001fОновлення Hub успішно завершено.\u001fНе вдалося оновити Hub.\u001fЗапит на оновлення відхилено.\u001fСлужба оновлення Hub ще не готова.\u001fHub не в мережі. Дочекайтеся підключення перед оновленням.\u001fЛише власник дому може розпочати оновлення.\u001fКритичне оновлення\u001fОновити зараз\u001fСпробувати знову\u001fПідтвердьте оновлення Hub\u001fОновити Hub до {release}? Hub може тимчасово відключитися. Не вимикайте живлення під час оновлення.\u001fЗапит на оновлення надіслано на Hub.\u001fНе вдалося надіслати запит на оновлення.",
      ro: "Actualizare Hub\u001fHub-ul este actualizat.\u001fVersiunea {release} este disponibilă.\u001fCererea a fost trimisă. Se așteaptă primirea de către Hub.\u001fHub-ul pregătește și instalează actualizarea.\u001fActualizarea Hub-ului s-a încheiat cu succes.\u001fActualizarea Hub-ului a eșuat.\u001fCererea de actualizare a fost respinsă.\u001fServiciul de actualizare al Hub-ului nu este pregătit.\u001fHub-ul este offline. Așteptați să revină online înainte de actualizare.\u001fDoar proprietarul casei poate porni o actualizare.\u001fActualizare critică\u001fActualizează acum\u001fÎncearcă din nou\u001fConfirmă actualizarea Hub-ului\u001fActualizați Hub-ul la {release}? Se poate deconecta temporar. Nu întrerupeți alimentarea în timpul actualizării.\u001fCererea de actualizare a fost trimisă către Hub.\u001fCererea de actualizare nu a putut fi trimisă.",
      hu: "Hub frissítése\u001fA Hub naprakész.\u001fA(z) {release} verzió elérhető.\u001fA kérés elküldve. Várakozás a Hub fogadására.\u001fA Hub előkészíti és telepíti a frissítést.\u001fA Hub frissítése sikeres.\u001fA Hub frissítése sikertelen.\u001fA frissítési kérelmet elutasították.\u001fA Hub frissítési szolgáltatása még nem áll készen.\u001fA Hub offline. Várja meg, amíg online lesz.\u001fCsak az otthon tulajdonosa indíthat frissítést.\u001fKritikus frissítés\u001fFrissítés most\u001fÚjra\u001fHub-frissítés megerősítése\u001fFrissíti a Hubot erre: {release}? Átmenetileg megszakadhat a kapcsolat. Frissítés közben ne húzza ki a tápellátást.\u001fA frissítési kérelem elküldve a Hubnak.\u001fA frissítési kérelmet nem sikerült elküldeni.",
      bg: "Актуализация на Hub\u001fHub е с най-новата версия.\u001fВерсия {release} е налична.\u001fЗаявката е изпратена. Изчаква се Hub да я получи.\u001fHub подготвя и инсталира актуализацията.\u001fАктуализацията на Hub завърши успешно.\u001fАктуализацията на Hub е неуспешна.\u001fЗаявката за актуализация беше отхвърлена.\u001fУслугата за актуализация на Hub още не е готова.\u001fHub е офлайн. Изчакайте да бъде онлайн преди актуализация.\u001fСамо собственикът на дома може да стартира актуализация.\u001fКритична актуализация\u001fАктуализирай сега\u001fОпитай отново\u001fПотвърждаване на актуализацията\u001fДа се актуализира Hub до {release}? Възможно е временно прекъсване. Не изключвайте захранването по време на актуализацията.\u001fЗаявката за актуализация е изпратена до Hub.\u001fЗаявката за актуализация не може да бъде изпратена.",
      hr: "Ažuriranje Huba\u001fHub je ažuriran.\u001fDostupna je verzija {release}.\u001fZahtjev je poslan. Čeka se da ga Hub primi.\u001fHub priprema i instalira ažuriranje.\u001fAžuriranje Huba uspješno je završeno.\u001fAžuriranje Huba nije uspjelo.\u001fZahtjev za ažuriranje je odbijen.\u001fUsluga ažuriranja Huba još nije spremna.\u001fHub je izvan mreže. Pričekajte da bude na mreži.\u001fSamo vlasnik doma može pokrenuti ažuriranje.\u001fKritično ažuriranje\u001fAžuriraj sada\u001fPokušaj ponovno\u001fPotvrdi ažuriranje Huba\u001fAžurirati Hub na {release}? Veza se može privremeno prekinuti. Ne isključujte napajanje tijekom ažuriranja.\u001fZahtjev za ažuriranje poslan je Hubu.\u001fZahtjev za ažuriranje nije moguće poslati.",
      sr: "Ažuriranje Huba\u001fHub je ažuriran.\u001fDostupna je verzija {release}.\u001fZahtev je poslat. Čeka se da ga Hub primi.\u001fHub priprema i instalira ažuriranje.\u001fAžuriranje Huba je uspešno završeno.\u001fAžuriranje Huba nije uspelo.\u001fZahtev za ažuriranje je odbijen.\u001fUsluga ažuriranja Huba još nije spremna.\u001fHub je van mreže. Sačekajte da bude na mreži.\u001fSamo vlasnik doma može pokrenuti ažuriranje.\u001fKritično ažuriranje\u001fAžuriraj sada\u001fPokušaj ponovo\u001fPotvrdi ažuriranje Huba\u001fAžurirati Hub na {release}? Veza može privremeno da se prekine. Ne isključujte napajanje tokom ažuriranja.\u001fZahtev za ažuriranje je poslat Hubu.\u001fZahtev za ažuriranje nije moguće poslati.",
      bs: "Ažuriranje Huba\u001fHub je ažuriran.\u001fDostupna je verzija {release}.\u001fZahtjev je poslan. Čeka se da ga Hub primi.\u001fHub priprema i instalira ažuriranje.\u001fAžuriranje Huba je uspješno završeno.\u001fAžuriranje Huba nije uspjelo.\u001fZahtjev za ažuriranje je odbijen.\u001fUsluga ažuriranja Huba još nije spremna.\u001fHub je van mreže. Sačekajte da bude na mreži.\u001fSamo vlasnik doma može pokrenuti ažuriranje.\u001fKritično ažuriranje\u001fAžuriraj sada\u001fPokušaj ponovo\u001fPotvrdi ažuriranje Huba\u001fAžurirati Hub na {release}? Veza može privremeno biti prekinuta. Ne isključujte napajanje tokom ažuriranja.\u001fZahtjev za ažuriranje je poslan Hubu.\u001fZahtjev za ažuriranje nije moguće poslati.",
      sl: "Posodobitev Huba\u001fHub je posodobljen.\u001fRazličica {release} je na voljo.\u001fZahteva je poslana. Čakanje, da jo Hub prejme.\u001fHub pripravlja in namešča posodobitev.\u001fPosodobitev Huba je uspela.\u001fPosodobitev Huba ni uspela.\u001fZahteva za posodobitev je bila zavrnjena.\u001fStoritev posodabljanja Huba še ni pripravljena.\u001fHub je brez povezave. Pred posodobitvijo počakajte, da bo povezan.\u001fPosodobitev lahko začne samo lastnik doma.\u001fKritična posodobitev\u001fPosodobi zdaj\u001fPoskusi znova\u001fPotrdi posodobitev Huba\u001fPosodobiti Hub na {release}? Povezava se lahko začasno prekine. Med posodobitvijo ne izklapljajte napajanja.\u001fZahteva za posodobitev je bila poslana Hubu.\u001fZahteve za posodobitev ni mogoče poslati.",
      mk: "Ажурирање на Hub\u001fHub е ажуриран.\u001fДостапна е верзијата {release}.\u001fБарањето е испратено. Се чека Hub да го прими.\u001fHub ја подготвува и инсталира надградбата.\u001fАжурирањето на Hub е успешно.\u001fАжурирањето на Hub не успеа.\u001fБарањето за ажурирање е одбиено.\u001fУслугата за ажурирање на Hub сè уште не е подготвена.\u001fHub е офлајн. Почекајте да биде онлајн.\u001fСамо сопственикот на домот може да започне ажурирање.\u001fКритично ажурирање\u001fАжурирај сега\u001fОбиди се повторно\u001fПотврди ажурирање на Hub\u001fДа се ажурира Hub на {release}? Може привремено да се исклучи. Не исклучувајте го напојувањето за време на ажурирањето.\u001fБарањето за ажурирање е испратено до Hub.\u001fБарањето за ажурирање не може да се испрати.",
      sq: "Përditësimi i Hub-it\u001fHub-i është i përditësuar.\u001fVersioni {release} është gati.\u001fKërkesa u dërgua. Po pritet që Hub-i ta marrë.\u001fHub-i po përgatit dhe instalon përditësimin.\u001fPërditësimi i Hub-it përfundoi me sukses.\u001fPërditësimi i Hub-it dështoi.\u001fKërkesa për përditësim u refuzua.\u001fShërbimi i përditësimit të Hub-it nuk është gati.\u001fHub-i është jashtë linje. Prisni të lidhet para përditësimit.\u001fVetëm pronari i shtëpisë mund të nisë përditësimin.\u001fPërditësim kritik\u001fPërditëso tani\u001fProvo përsëri\u001fKonfirmo përditësimin e Hub-it\u001fTë përditësohet Hub-i në {release}? Mund të shkëputet përkohësisht. Mos e hiqni nga rryma gjatë përditësimit.\u001fKërkesa për përditësim iu dërgua Hub-it.\u001fKërkesa për përditësim nuk mund të dërgohej.",
      el: "Ενημέρωση Hub\u001fΤο Hub είναι ενημερωμένο.\u001fΗ έκδοση {release} είναι διαθέσιμη.\u001fΤο αίτημα στάλθηκε. Αναμονή παραλαβής από το Hub.\u001fΤο Hub προετοιμάζει και εγκαθιστά την ενημέρωση.\u001fΗ ενημέρωση του Hub ολοκληρώθηκε.\u001fΗ ενημέρωση του Hub απέτυχε.\u001fΤο αίτημα ενημέρωσης απορρίφθηκε.\u001fΗ υπηρεσία ενημέρωσης του Hub δεν είναι έτοιμη.\u001fΤο Hub είναι εκτός σύνδεσης. Περιμένετε να συνδεθεί πριν την ενημέρωση.\u001fΜόνο ο ιδιοκτήτης του σπιτιού μπορεί να ξεκινήσει ενημέρωση.\u001fΚρίσιμη ενημέρωση\u001fΕνημέρωση τώρα\u001fΔοκιμή ξανά\u001fΕπιβεβαίωση ενημέρωσης Hub\u001fΕνημέρωση του Hub στην έκδοση {release}; Μπορεί να αποσυνδεθεί προσωρινά. Μην διακόψετε την τροφοδοσία κατά την ενημέρωση.\u001fΤο αίτημα ενημέρωσης στάλθηκε στο Hub.\u001fΔεν ήταν δυνατή η αποστολή του αιτήματος ενημέρωσης.",
      tr: "Hub güncellemesi\u001fHub güncel.\u001f{release} sürümü hazır.\u001fİstek gönderildi. Hub’ın alması bekleniyor.\u001fHub güncellemeyi hazırlıyor ve yüklüyor.\u001fHub güncellemesi başarıyla tamamlandı.\u001fHub güncellemesi başarısız oldu.\u001fGüncelleme isteği reddedildi.\u001fHub güncelleme hizmeti henüz hazır değil.\u001fHub çevrimdışı. Güncellemeden önce çevrimiçi olmasını bekleyin.\u001fGüncellemeyi yalnızca Ev Sahibi başlatabilir.\u001fKritik güncelleme\u001fŞimdi güncelle\u001fTekrar dene\u001fHub güncellemesini onayla\u001fHub {release} sürümüne güncellensin mi? Geçici olarak bağlantı kesilebilir. Güncelleme sırasında gücü kesmeyin.\u001fGüncelleme isteği Hub’a gönderildi.\u001fGüncelleme isteği gönderilemedi.",
      sv: "Hub-uppdatering\u001fHubben är uppdaterad.\u001fVersion {release} är tillgänglig.\u001fBegäran har skickats. Väntar på att Hubben tar emot den.\u001fHubben förbereder och installerar uppdateringen.\u001fHub-uppdateringen slutfördes.\u001fHub-uppdateringen misslyckades.\u001fUppdateringsbegäran avvisades.\u001fHubbens uppdateringstjänst är inte klar.\u001fHubben är offline. Vänta tills den är online innan du uppdaterar.\u001fEndast hemmets ägare kan starta en uppdatering.\u001fKritisk uppdatering\u001fUppdatera nu\u001fFörsök igen\u001fBekräfta Hub-uppdatering\u001fUppdatera Hubben till {release}? Den kan kopplas från tillfälligt. Koppla inte ur strömmen under uppdateringen.\u001fUppdateringsbegäran skickades till Hubben.\u001fDet gick inte att skicka uppdateringsbegäran.",
      da: "Hub-opdatering\u001fHubben er opdateret.\u001fVersion {release} er tilgængelig.\u001fAnmodningen er sendt. Venter på at Hubben modtager den.\u001fHubben forbereder og installerer opdateringen.\u001fHub-opdateringen blev gennemført.\u001fHub-opdateringen mislykkedes.\u001fOpdateringsanmodningen blev afvist.\u001fHubbens opdateringstjeneste er ikke klar.\u001fHubben er offline. Vent til den er online før opdatering.\u001fKun boligens ejer kan starte en opdatering.\u001fKritisk opdatering\u001fOpdater nu\u001fPrøv igen\u001fBekræft Hub-opdatering\u001fOpdater Hubben til {release}? Den kan blive midlertidigt afbrudt. Afbryd ikke strømmen under opdateringen.\u001fOpdateringsanmodningen blev sendt til Hubben.\u001fOpdateringsanmodningen kunne ikke sendes.",
      nb: "Hub-oppdatering\u001fHuben er oppdatert.\u001fVersjon {release} er tilgjengelig.\u001fForespørselen er sendt. Venter på at Huben mottar den.\u001fHuben forbereder og installerer oppdateringen.\u001fHub-oppdateringen ble fullført.\u001fHub-oppdateringen mislyktes.\u001fOppdateringsforespørselen ble avvist.\u001fHubens oppdateringstjeneste er ikke klar.\u001fHuben er frakoblet. Vent til den er tilkoblet før oppdatering.\u001fBare boligeieren kan starte en oppdatering.\u001fKritisk oppdatering\u001fOppdater nå\u001fPrøv igjen\u001fBekreft Hub-oppdatering\u001fOppdatere Huben til {release}? Den kan kobles fra midlertidig. Ikke koble fra strømmen under oppdateringen.\u001fOppdateringsforespørselen ble sendt til Huben.\u001fOppdateringsforespørselen kunne ikke sendes.",
      fi: "Hubin päivitys\u001fHub on ajan tasalla.\u001fVersio {release} on saatavilla.\u001fPyyntö lähetetty. Odotetaan, että Hub vastaanottaa sen.\u001fHub valmistelee ja asentaa päivitystä.\u001fHubin päivitys onnistui.\u001fHubin päivitys epäonnistui.\u001fPäivityspyyntö hylättiin.\u001fHubin päivityspalvelu ei ole valmis.\u001fHub ei ole verkossa. Odota, että se on verkossa ennen päivitystä.\u001fVain kodin omistaja voi aloittaa päivityksen.\u001fKriittinen päivitys\u001fPäivitä nyt\u001fYritä uudelleen\u001fVahvista Hubin päivitys\u001fPäivitetäänkö Hub versioon {release}? Yhteys voi katketa tilapäisesti. Älä irrota virtaa päivityksen aikana.\u001fPäivityspyyntö lähetettiin Hubille.\u001fPäivityspyyntöä ei voitu lähettää.",
      isLang: "Uppfærsla Hub\u001fHub er uppfært.\u001fÚtgáfa {release} er tiltæk.\u001fBeiðni send. Beðið eftir að Hub taki við henni.\u001fHub undirbýr og setur upp uppfærsluna.\u001fUppfærsla Hub tókst.\u001fUppfærsla Hub mistókst.\u001fUppfærslubeiðninni var hafnað.\u001fUppfærsluþjónusta Hub er ekki tilbúin.\u001fHub er ótengt. Bíddu þar til það tengist áður en þú uppfærir.\u001fAðeins eigandi heimilisins getur hafið uppfærslu.\u001fMikilvæg uppfærsla\u001fUppfæra núna\u001fReyna aftur\u001fStaðfesta uppfærslu Hub\u001fUppfæra Hub í {release}? Það getur aftengst tímabundið. Ekki taka rafmagn úr sambandi meðan á uppfærslu stendur.\u001fUppfærslubeiðnin var send til Hub.\u001fEkki tókst að senda uppfærslubeiðnina.",
      et: "Hubi värskendus\u001fHub on ajakohane.\u001fVersioon {release} on saadaval.\u001fTaotlus saadeti. Oodatakse, et Hub selle vastu võtaks.\u001fHub valmistab värskendust ette ja installib seda.\u001fHubi värskendus õnnestus.\u001fHubi värskendus ebaõnnestus.\u001fVärskendustaotlus lükati tagasi.\u001fHubi värskendusteenus pole veel valmis.\u001fHub on võrguühenduseta. Oodake enne värskendamist, kuni see on võrgus.\u001fAinult kodu omanik saab värskenduse käivitada.\u001fKriitiline värskendus\u001fVärskenda kohe\u001fProovi uuesti\u001fKinnita Hubi värskendus\u001fVärskendada Hub versioonile {release}? Ühendus võib ajutiselt katkeda. Ärge eemaldage värskendamise ajal toidet.\u001fVärskendustaotlus saadeti Hubile.\u001fVärskendustaotlust ei saanud saata.",
      lv: "Hub atjauninājums\u001fHub ir atjaunināts.\u001fIr pieejama versija {release}.\u001fPieprasījums nosūtīts. Gaida, līdz Hub to saņems.\u001fHub sagatavo un instalē atjauninājumu.\u001fHub atjauninājums pabeigts veiksmīgi.\u001fHub atjauninājums neizdevās.\u001fAtjaunināšanas pieprasījums tika noraidīts.\u001fHub atjaunināšanas pakalpojums vēl nav gatavs.\u001fHub ir bezsaistē. Pirms atjaunināšanas gaidiet, līdz tas būs tiešsaistē.\u001fTikai mājas īpašnieks var sākt atjaunināšanu.\u001fKritisks atjauninājums\u001fAtjaunināt tagad\u001fMēģināt vēlreiz\u001fApstiprināt Hub atjauninājumu\u001fAtjaunināt Hub uz {release}? Tas var īslaicīgi atvienoties. Atjaunināšanas laikā neatvienojiet barošanu.\u001fAtjaunināšanas pieprasījums nosūtīts Hub.\u001fAtjaunināšanas pieprasījumu nevarēja nosūtīt.",
      lt: "Hub atnaujinimas\u001fHub yra atnaujintas.\u001fPasiekiama versija {release}.\u001fUžklausa išsiųsta. Laukiama, kol Hub ją gaus.\u001fHub ruošia ir diegia atnaujinimą.\u001fHub atnaujinimas sėkmingas.\u001fHub atnaujinimas nepavyko.\u001fAtnaujinimo užklausa atmesta.\u001fHub atnaujinimo paslauga dar neparuošta.\u001fHub neprisijungęs. Prieš atnaujindami palaukite, kol prisijungs.\u001fTik namų savininkas gali pradėti atnaujinimą.\u001fKritinis atnaujinimas\u001fAtnaujinti dabar\u001fBandyti dar kartą\u001fPatvirtinti Hub atnaujinimą\u001fAtnaujinti Hub į {release}? Jis gali laikinai atsijungti. Atnaujinimo metu neatjunkite maitinimo.\u001fAtnaujinimo užklausa išsiųsta Hub.\u001fNepavyko išsiųsti atnaujinimo užklausos.",
      ga: "Nuashonrú Hub\u001fTá an Hub cothrom le dáta.\u001fTá leagan {release} ar fáil.\u001fSeoladh an t-iarratas. Ag fanacht leis an Hub é a fháil.\u001fTá an Hub ag ullmhú agus ag suiteáil an nuashonraithe.\u001fD’éirigh le nuashonrú an Hub.\u001fTheip ar nuashonrú an Hub.\u001fDiúltaíodh don iarratas nuashonraithe.\u001fNíl seirbhís nuashonraithe an Hub réidh fós.\u001fTá an Hub as líne. Fan go mbeidh sé ar líne roimh nuashonrú.\u001fIs é úinéir an tí amháin atá in ann nuashonrú a thosú.\u001fNuashonrú criticiúil\u001fNuashonraigh anois\u001fBain triail eile as\u001fDeimhnigh nuashonrú an Hub\u001fAn Hub a nuashonrú go {release}? D’fhéadfadh sé dícheangal go sealadach. Ná bain an chumhacht le linn an nuashonraithe.\u001fSeoladh an t-iarratas nuashonraithe chuig an Hub.\u001fNíorbh fhéidir an t-iarratas nuashonraithe a sheoladh.",
      mt: "Aġġornament tal-Hub\u001fIl-Hub huwa aġġornat.\u001fIl-verżjoni {release} hija disponibbli.\u001fIt-talba ntbagħtet. Qed tistenna li l-Hub jirċeviha.\u001fIl-Hub qed jipprepara u jinstalla l-aġġornament.\u001fL-aġġornament tal-Hub irnexxa.\u001fL-aġġornament tal-Hub falla.\u001fIt-talba għall-aġġornament ġiet miċħuda.\u001fIs-servizz tal-aġġornament tal-Hub għadu mhux lest.\u001fIl-Hub huwa offline. Stenna sakemm ikun online qabel taġġorna.\u001fIs-sid tad-dar biss jista’ jibda aġġornament.\u001fAġġornament kritiku\u001fAġġorna issa\u001fErġa’ pprova\u001fIkkonferma l-aġġornament tal-Hub\u001fTaġġorna l-Hub għal {release}? Jista’ jiskonnettja temporanjament. Taqtax l-enerġija waqt l-aġġornament.\u001fIt-talba għall-aġġornament intbagħtet lill-Hub.\u001fMa setgħetx tintbagħat it-talba għall-aġġornament.",
      be: "Абнаўленне Hub\u001fНа Hub усталявана апошняя версія.\u001fДаступная версія {release}.\u001fЗапыт адпраўлены. Чаканне атрымання Hub.\u001fHub рыхтуе і ўсталёўвае абнаўленне.\u001fАбнаўленне Hub паспяхова завершана.\u001fНе ўдалося абнавіць Hub.\u001fЗапыт на абнаўленне адхілены.\u001fСлужба абнаўлення Hub яшчэ не гатова.\u001fHub не ў сетцы. Дачакайцеся падключэння перад абнаўленнем.\u001fТолькі ўладальнік дома можа пачаць абнаўленне.\u001fКрытычнае абнаўленне\u001fАбнавіць зараз\u001fПаўтарыць\u001fПацвердзіць абнаўленне Hub\u001fАбнавіць Hub да {release}? Hub можа часова адключыцца. Не выключайце сілкаванне падчас абнаўлення.\u001fЗапыт на абнаўленне адпраўлены на Hub.\u001fНе ўдалося адправіць запыт на абнаўленне.",
      lb: "Hub-Aktualiséierung\u001fDen Hub ass aktuell.\u001fVersioun {release} ass verfügbar.\u001fUfro geschéckt. Waarden, bis den Hub se kritt.\u001fDen Hub bereet d’Aktualiséierung vir an installéiert se.\u001fHub-Aktualiséierung erfollegräich.\u001fHub-Aktualiséierung feelgeschloen.\u001fD’Aktualiséierungsufro gouf refuséiert.\u001fDen Aktualiséierungsdéngscht vum Hub ass nach net prett.\u001fDen Hub ass offline. Waart bis en online ass.\u001fNëmmen den Hausbesëtzer kann eng Aktualiséierung starten.\u001fKritesch Aktualiséierung\u001fElo aktualiséieren\u001fNach eng Kéier probéieren\u001fHub-Aktualiséierung bestätegen\u001fDen Hub op {release} aktualiséieren? E kann temporär getrennt ginn. Trennt de Stroum net wärend der Aktualiséierung.\u001fD’Aktualiséierungsufro gouf un den Hub geschéckt.\u001fD’Aktualiséierungsufro konnt net geschéckt ginn.",
      ca: "Actualització del Hub\u001fEl Hub està actualitzat.\u001fLa versió {release} està disponible.\u001fS’ha enviat la sol·licitud. S’espera que el Hub la rebi.\u001fEl Hub prepara i instal·la l’actualització.\u001fL’actualització del Hub s’ha completat.\u001fL’actualització del Hub ha fallat.\u001fLa sol·licitud d’actualització ha estat rebutjada.\u001fEl servei d’actualització del Hub encara no està preparat.\u001fEl Hub està fora de línia. Espereu que estigui en línia abans d’actualitzar.\u001fNomés el propietari de la llar pot iniciar una actualització.\u001fActualització crítica\u001fActualitza ara\u001fTorna-ho a provar\u001fConfirma l’actualització del Hub\u001fVoleu actualitzar el Hub a {release}? Pot desconnectar-se temporalment. No desconnecteu l’alimentació durant l’actualització.\u001fLa sol·licitud d’actualització s’ha enviat al Hub.\u001fNo s’ha pogut enviar la sol·licitud d’actualització.",
      cnr: "Ažuriranje Huba\u001fHub je ažuriran.\u001fDostupna je verzija {release}.\u001fZahtev je poslat. Čeka se da ga Hub primi.\u001fHub priprema i instalira ažuriranje.\u001fAžuriranje Huba je uspešno završeno.\u001fAžuriranje Huba nije uspelo.\u001fZahtev za ažuriranje je odbijen.\u001fUsluga ažuriranja Huba još nije spremna.\u001fHub je van mreže. Sačekajte da bude na mreži.\u001fSamo vlasnik doma može pokrenuti ažuriranje.\u001fKritično ažuriranje\u001fAžuriraj sada\u001fPokušaj ponovo\u001fPotvrdi ažuriranje Huba\u001fAžurirati Hub na {release}? Veza može privremeno da se prekine. Ne isključujte napajanje tokom ažuriranja.\u001fZahtev za ažuriranje je poslat Hubu.\u001fZahtev za ažuriranje nije moguće poslati.",
      hy: "Hub-ի թարմացում\u001fHub-ը արդիական է։\u001f{release} տարբերակը հասանելի է։\u001fՀարցումն ուղարկվել է։ Սպասում է, որ Hub-ը ստանա այն։\u001fHub-ը պատրաստում և տեղադրում է թարմացումը։\u001fHub-ի թարմացումը հաջողվեց։\u001fHub-ի թարմացումը ձախողվեց։\u001fԹարմացման հարցումը մերժվել է։\u001fHub-ի թարմացման ծառայությունը դեռ պատրաստ չէ։\u001fHub-ը անցանց է։ Թարմացնելուց առաջ սպասեք, մինչև առցանց լինի։\u001fԹարմացումը կարող է սկսել միայն տան սեփականատերը։\u001fԿարևոր թարմացում\u001fԹարմացնել հիմա\u001fԿրկին փորձել\u001fՀաստատել Hub-ի թարմացումը\u001fԹարմացնե՞լ Hub-ը {release} տարբերակին։ Այն կարող է ժամանակավորապես անջատվել։ Թարմացման ընթացքում մի անջատեք հոսանքը։\u001fԹարմացման հարցումն ուղարկվել է Hub-ին։\u001fՉհաջողվեց ուղարկել թարմացման հարցումը։",
      ka: "Hub-ის განახლება\u001fHub განახლებულია.\u001fხელმისაწვდომია ვერსია {release}.\u001fმოთხოვნა გაიგზავნა. ველოდებით Hub-ის მიღებას.\u001fHub ამზადებს და აყენებს განახლებას.\u001fHub-ის განახლება წარმატებით დასრულდა.\u001fHub-ის განახლება ვერ მოხერხდა.\u001fგანახლების მოთხოვნა უარყოფილია.\u001fHub-ის განახლების სერვისი ჯერ მზად არ არის.\u001fHub ხაზგარეშეა. განახლებამდე დაელოდეთ ონლაინ დაბრუნებას.\u001fგანახლების დაწყება მხოლოდ სახლის მფლობელს შეუძლია.\u001fკრიტიკული განახლება\u001fახლავე განახლება\u001fხელახლა ცდა\u001fHub-ის განახლების დადასტურება\u001fგანახლდეს Hub {release} ვერსიაზე? შესაძლოა დროებით გაითიშოს. განახლებისას ნუ გამორთავთ კვებას.\u001fგანახლების მოთხოვნა გაიგზავნა Hub-ზე.\u001fგანახლების მოთხოვნის გაგზავნა ვერ მოხერხდა.",
      az: "Hub yeniləməsi\u001fHub ən son versiyadadır.\u001f{release} versiyası hazırdır.\u001fSorğu göndərildi. Hub-ın qəbul etməsi gözlənilir.\u001fHub yeniləməni hazırlayır və quraşdırır.\u001fHub yeniləməsi uğurla tamamlandı.\u001fHub yeniləməsi uğursuz oldu.\u001fYeniləmə sorğusu rədd edildi.\u001fHub yeniləmə xidməti hələ hazır deyil.\u001fHub oflayndır. Yeniləmədən əvvəl onlayn olmasını gözləyin.\u001fYeniləməni yalnız ev sahibi başlada bilər.\u001fKritik yeniləmə\u001fİndi yenilə\u001fYenidən cəhd et\u001fHub yeniləməsini təsdiqlə\u001fHub {release} versiyasına yenilənsin? Müvəqqəti olaraq bağlantı kəsilə bilər. Yeniləmə zamanı enerjini ayırmayın.\u001fYeniləmə sorğusu Hub-a göndərildi.\u001fYeniləmə sorğusu göndərilə bilmədi.",
    ).split('\u001f');

    assert(
      values.length == _expectedHubUpdateStringCount,
      'Invalid Hub update localization bundle.',
    );

    return values;
  }

  String _hubUpdateText(int index) {
    final values = _hubUpdateBundle;

    if (index < 0 || index >= values.length) {
      return '';
    }

    return values[index];
  }

  String get hubUpdateSectionTitle => _hubUpdateText(0);
  String get hubUpdateUpToDateText => _hubUpdateText(1);

  String hubUpdateAvailableText(String releaseId) =>
      _hubUpdateText(2).replaceAll('{release}', releaseId);

  String get hubUpdateWaitingText => _hubUpdateText(3);
  String get hubUpdateInstallingText => _hubUpdateText(4);
  String get hubUpdateSuccessText => _hubUpdateText(5);
  String get hubUpdateFailedText => _hubUpdateText(6);
  String get hubUpdateRejectedText => _hubUpdateText(7);
  String get hubUpdateAgentUnavailableText => _hubUpdateText(8);
  String get hubUpdateOfflineText => _hubUpdateText(9);
  String get hubUpdateOwnerOnlyText => _hubUpdateText(10);
  String get hubUpdateCriticalText => _hubUpdateText(11);
  String get hubUpdateButtonText => _hubUpdateText(12);
  String get hubUpdateRetryButtonText => _hubUpdateText(13);
  String get hubUpdateConfirmTitle => _hubUpdateText(14);

  String hubUpdateConfirmMessage(String releaseId) =>
      _hubUpdateText(15).replaceAll('{release}', releaseId);

  String get hubUpdateRequestSentText => _hubUpdateText(16);
  String get hubUpdateRequestFailedText => _hubUpdateText(17);
}
