import 'app_strings.dart';

extension SystemVersionStrings on AppStrings {
  String get systemVersionsTitle => choose(
    vi: 'Phiên bản hệ thống',
    en: 'System versions',
    zh: '系统版本',
    ko: '시스템 버전',
    ja: 'システムバージョン',
    de: 'Systemversionen',
    ru: 'Версии системы',
    fr: 'Versions du système',
    es: 'Versiones del sistema',
    id: 'Versi sistem',
    th: 'เวอร์ชันระบบ',
    ms: 'Versi sistem',
    fil: 'Mga bersyon ng system',
    km: 'កំណែប្រព័ន្ធ',
    my: 'စနစ်ဗားရှင်းများ',
    lo: 'ເວີຊັນລະບົບ',
    ta: 'கணினி பதிப்புகள்',
    pt: 'Versões do sistema',
    tet: 'Versaun sistema',
    it: 'Versioni di sistema',
    pl: 'Wersje systemu',
    nl: 'Systeemversies',
    cs: 'Verze systému',
    sk: 'Verzie systému',
    uk: 'Версії системи',
    ro: 'Versiuni de sistem',
    hu: 'Rendszerverziók',
    bg: 'Версии на системата',
    hr: 'Verzije sustava',
    sr: 'Verzije sistema',
    bs: 'Verzije sistema',
    sl: 'Različice sistema',
    mk: 'Верзии на системот',
    sq: 'Versionet e sistemit',
    el: 'Εκδόσεις συστήματος',
    tr: 'Sistem sürümleri',
    sv: 'Systemversioner',
    da: 'Systemversioner',
    nb: 'Systemversjoner',
    fi: 'Järjestelmäversiot',
    isLang: 'Kerfisútgáfur',
    et: 'Süsteemi versioonid',
    lv: 'Sistēmas versijas',
    lt: 'Sistemos versijos',
    ga: 'Leaganacha córais',
    mt: 'Verżjonijiet tas-sistema',
    be: 'Версіі сістэмы',
    lb: 'Systemversiounen',
    ca: 'Versions del sistema',
    cnr: 'Verzije sistema',
    hy: 'Համակարգի տարբերակներ',
    ka: 'სისტემის ვერსიები',
    az: 'Sistem versiyaları',
  );

  String get appVersionLabel => choose(
    vi: 'Phiên bản ứng dụng',
    en: 'App version',
    zh: '应用版本',
    ko: '앱 버전',
    ja: 'アプリバージョン',
    de: 'App-Version',
    ru: 'Версия приложения',
    fr: 'Version de l’application',
    es: 'Versión de la aplicación',
    id: 'Versi aplikasi',
    th: 'เวอร์ชันแอป',
    ms: 'Versi aplikasi',
    fil: 'Bersyon ng app',
    km: 'កំណែកម្មវិធី',
    my: 'အက်ပ်ဗားရှင်း',
    lo: 'ເວີຊັນແອັບ',
    ta: 'செயலி பதிப்பு',
    pt: 'Versão do aplicativo',
    tet: 'Versaun aplikasaun',
    it: 'Versione app',
    pl: 'Wersja aplikacji',
    nl: 'App-versie',
    cs: 'Verze aplikace',
    sk: 'Verzia aplikácie',
    uk: 'Версія застосунку',
    ro: 'Versiunea aplicației',
    hu: 'Alkalmazásverzió',
    bg: 'Версия на приложението',
    hr: 'Verzija aplikacije',
    sr: 'Verzija aplikacije',
    bs: 'Verzija aplikacije',
    sl: 'Različica aplikacije',
    mk: 'Верзија на апликацијата',
    sq: 'Versioni i aplikacionit',
    el: 'Έκδοση εφαρμογής',
    tr: 'Uygulama sürümü',
    sv: 'Appversion',
    da: 'Appversion',
    nb: 'Appversjon',
    fi: 'Sovellusversio',
    isLang: 'Útgáfa apps',
    et: 'Rakenduse versioon',
    lv: 'Lietotnes versija',
    lt: 'Programėlės versija',
    ga: 'Leagan na haipe',
    mt: 'Verżjoni tal-app',
    be: 'Версія праграмы',
    lb: 'App-Versioun',
    ca: 'Versió de l’aplicació',
    cnr: 'Verzija aplikacije',
    hy: 'Հավելվածի տարբերակ',
    ka: 'აპის ვერსია',
    az: 'Tətbiq versiyası',
  );

  String get backendVersionLabel => choose(
    vi: 'Phiên bản Backend',
    en: 'Backend version',
    zh: '后端版本',
    ko: '백엔드 버전',
    ja: 'バックエンドバージョン',
    de: 'Backend-Version',
    ru: 'Версия Backend',
    fr: 'Version du backend',
    es: 'Versión del backend',
    id: 'Versi backend',
    th: 'เวอร์ชันแบ็กเอนด์',
    ms: 'Versi backend',
    fil: 'Bersyon ng backend',
    km: 'កំណែ Backend',
    my: 'Backend ဗားရှင်း',
    lo: 'ເວີຊັນ Backend',
    ta: 'Backend பதிப்பு',
    pt: 'Versão do backend',
    tet: 'Versaun backend',
    it: 'Versione backend',
    pl: 'Wersja backendu',
    nl: 'Backend-versie',
    cs: 'Verze backendu',
    sk: 'Verzia backendu',
    uk: 'Версія backend',
    ro: 'Versiunea backendului',
    hu: 'Backend verzió',
    bg: 'Версия на backend',
    hr: 'Verzija backenda',
    sr: 'Verzija backenda',
    bs: 'Verzija backenda',
    sl: 'Različica zaledja',
    mk: 'Верзија на backend',
    sq: 'Versioni i backend-it',
    el: 'Έκδοση backend',
    tr: 'Backend sürümü',
    sv: 'Backendversion',
    da: 'Backendversion',
    nb: 'Backendversjon',
    fi: 'Backend-versio',
    isLang: 'Backend-útgáfa',
    et: 'Backend-versioon',
    lv: 'Backend versija',
    lt: 'Backend versija',
    ga: 'Leagan backend',
    mt: 'Verżjoni backend',
    be: 'Версія backend',
    lb: 'Backend-Versioun',
    ca: 'Versió del backend',
    cnr: 'Verzija backenda',
    hy: 'Backend-ի տարբերակ',
    ka: 'Backend-ის ვერსია',
    az: 'Backend versiyası',
  );

  String get hubFirmwareVersionLabel => choose(
    vi: 'Phiên bản Firmware Hub',
    en: 'Hub firmware version',
    zh: 'Hub 固件版本',
    ko: 'Hub 펌웨어 버전',
    ja: 'Hubファームウェアバージョン',
    de: 'Hub-Firmware-Version',
    ru: 'Версия прошивки Hub',
    fr: 'Version du firmware du Hub',
    es: 'Versión del firmware del Hub',
    id: 'Versi firmware Hub',
    th: 'เวอร์ชันเฟิร์มแวร์ Hub',
    ms: 'Versi perisian tegar Hub',
    fil: 'Bersyon ng firmware ng Hub',
    km: 'កំណែ Firmware របស់ Hub',
    my: 'Hub firmware ဗားရှင်း',
    lo: 'ເວີຊັນ Firmware Hub',
    ta: 'Hub firmware பதிப்பு',
    pt: 'Versão do firmware do Hub',
    tet: 'Versaun firmware Hub',
    it: 'Versione firmware Hub',
    pl: 'Wersja firmware Hub',
    nl: 'Hub-firmwareversie',
    cs: 'Verze firmwaru Hubu',
    sk: 'Verzia firmvéru Hubu',
    uk: 'Версія прошивки Hub',
    ro: 'Versiunea firmware-ului Hub',
    hu: 'Hub firmware-verzió',
    bg: 'Версия на фърмуера на Hub',
    hr: 'Verzija firmvera Huba',
    sr: 'Verzija firmvera Huba',
    bs: 'Verzija firmvera Huba',
    sl: 'Različica vdelane programske opreme Huba',
    mk: 'Верзија на firmware на Hub',
    sq: 'Versioni i firmware-it të Hub-it',
    el: 'Έκδοση firmware Hub',
    tr: 'Hub ürün yazılımı sürümü',
    sv: 'Hub-firmwareversion',
    da: 'Hub-firmwareversion',
    nb: 'Hub-fastvareversjon',
    fi: 'Hub-laiteohjelmistoversio',
    isLang: 'Fastbúnaðarútgáfa Hub',
    et: 'Hubi püsivara versioon',
    lv: 'Hub programmaparatūras versija',
    lt: 'Hub programinės aparatinės įrangos versija',
    ga: 'Leagan firmware an Hub',
    mt: 'Verżjoni tal-firmware tal-Hub',
    be: 'Версія прашыўкі Hub',
    lb: 'Hub-Firmware-Versioun',
    ca: 'Versió del firmware del Hub',
    cnr: 'Verzija firmvera Huba',
    hy: 'Hub firmware-ի տարբերակ',
    ka: 'Hub firmware-ის ვერსია',
    az: 'Hub firmware versiyası',
  );

  String get protocolVersionLabel => choose(
    vi: 'Phiên bản giao thức',
    en: 'Protocol version',
    zh: '协议版本',
    ko: '프로토콜 버전',
    ja: 'プロトコルバージョン',
    de: 'Protokollversion',
    ru: 'Версия протокола',
    fr: 'Version du protocole',
    es: 'Versión del protocolo',
    id: 'Versi protokol',
    th: 'เวอร์ชันโปรโตคอล',
    ms: 'Versi protokol',
    fil: 'Bersyon ng protocol',
    km: 'កំណែពិធីការ',
    my: 'ပရိုတိုကောဗားရှင်း',
    lo: 'ເວີຊັນໂປຣໂຕຄອນ',
    ta: 'நெறிமுறை பதிப்பு',
    pt: 'Versão do protocolo',
    tet: 'Versaun protokolu',
    it: 'Versione protocollo',
    pl: 'Wersja protokołu',
    nl: 'Protocolversie',
    cs: 'Verze protokolu',
    sk: 'Verzia protokolu',
    uk: 'Версія протоколу',
    ro: 'Versiunea protocolului',
    hu: 'Protokollverzió',
    bg: 'Версия на протокола',
    hr: 'Verzija protokola',
    sr: 'Verzija protokola',
    bs: 'Verzija protokola',
    sl: 'Različica protokola',
    mk: 'Верзија на протоколот',
    sq: 'Versioni i protokollit',
    el: 'Έκδοση πρωτοκόλλου',
    tr: 'Protokol sürümü',
    sv: 'Protokollversion',
    da: 'Protokolversion',
    nb: 'Protokollversjon',
    fi: 'Protokollaversio',
    isLang: 'Samskiptaregluútgáfa',
    et: 'Protokolli versioon',
    lv: 'Protokola versija',
    lt: 'Protokolo versija',
    ga: 'Leagan prótacail',
    mt: 'Verżjoni tal-protokoll',
    be: 'Версія пратаколу',
    lb: 'Protokollversioun',
    ca: 'Versió del protocol',
    cnr: 'Verzija protokola',
    hy: 'Արձանագրության տարբերակ',
    ka: 'პროტოკოლის ვერსია',
    az: 'Protokol versiyası',
  );

  String get protocolCompatibilityLabel => choose(
    vi: 'Tương thích giao thức',
    en: 'Protocol compatibility',
    zh: '协议兼容性',
    ko: '프로토콜 호환성',
    ja: 'プロトコル互換性',
    de: 'Protokollkompatibilität',
    ru: 'Совместимость протокола',
    fr: 'Compatibilité du protocole',
    es: 'Compatibilidad del protocolo',
    id: 'Kompatibilitas protokol',
    th: 'ความเข้ากันได้ของโปรโตคอล',
    ms: 'Keserasian protokol',
    fil: 'Pagkakatugma ng protocol',
    km: 'ភាពឆបគ្នានៃពិធីការ',
    my: 'ပရိုတိုကော ကိုက်ညီမှု',
    lo: 'ຄວາມເຂົ້າກັນໄດ້ຂອງໂປຣໂຕຄອນ',
    ta: 'நெறிமுறை இணக்கத்தன்மை',
    pt: 'Compatibilidade do protocolo',
    tet: 'Kompatibilidade protokolu',
    it: 'Compatibilità del protocollo',
    pl: 'Zgodność protokołu',
    nl: 'Protocolcompatibiliteit',
    cs: 'Kompatibilita protokolu',
    sk: 'Kompatibilita protokolu',
    uk: 'Сумісність протоколу',
    ro: 'Compatibilitatea protocolului',
    hu: 'Protokoll-kompatibilitás',
    bg: 'Съвместимост на протокола',
    hr: 'Kompatibilnost protokola',
    sr: 'Kompatibilnost protokola',
    bs: 'Kompatibilnost protokola',
    sl: 'Združljivost protokola',
    mk: 'Компатибилност на протоколот',
    sq: 'Përputhshmëria e protokollit',
    el: 'Συμβατότητα πρωτοκόλλου',
    tr: 'Protokol uyumluluğu',
    sv: 'Protokollkompatibilitet',
    da: 'Protokolkompatibilitet',
    nb: 'Protokollkompatibilitet',
    fi: 'Protokollayhteensopivuus',
    isLang: 'Samhæfni samskiptareglu',
    et: 'Protokolli ühilduvus',
    lv: 'Protokola saderība',
    lt: 'Protokolo suderinamumas',
    ga: 'Comhoiriúnacht prótacail',
    mt: 'Kompatibbiltà tal-protokoll',
    be: 'Сумяшчальнасць пратаколу',
    lb: 'Protokollkompatibilitéit',
    ca: 'Compatibilitat del protocol',
    cnr: 'Kompatibilnost protokola',
    hy: 'Արձանագրության համատեղելիություն',
    ka: 'პროტოკოლის თავსებადობა',
    az: 'Protokol uyğunluğu',
  );

  String get protocolCompatibleText => choose(
    vi: 'Tương thích',
    en: 'Compatible',
    zh: '兼容',
    ko: '호환됨',
    ja: '互換性あり',
    de: 'Kompatibel',
    ru: 'Совместимо',
    fr: 'Compatible',
    es: 'Compatible',
    id: 'Kompatibel',
    th: 'เข้ากันได้',
    ms: 'Serasi',
    fil: 'Compatible',
    km: 'ឆបគ្នា',
    my: 'ကိုက်ညီသည်',
    lo: 'ເຂົ້າກັນໄດ້',
    ta: 'இணக்கமானது',
    pt: 'Compatível',
    tet: 'Kompatível',
    it: 'Compatibile',
    pl: 'Zgodny',
    nl: 'Compatibel',
    cs: 'Kompatibilní',
    sk: 'Kompatibilné',
    uk: 'Сумісно',
    ro: 'Compatibil',
    hu: 'Kompatibilis',
    bg: 'Съвместимо',
    hr: 'Kompatibilno',
    sr: 'Kompatibilno',
    bs: 'Kompatibilno',
    sl: 'Združljivo',
    mk: 'Компатибилно',
    sq: 'I përputhshëm',
    el: 'Συμβατό',
    tr: 'Uyumlu',
    sv: 'Kompatibel',
    da: 'Kompatibel',
    nb: 'Kompatibel',
    fi: 'Yhteensopiva',
    isLang: 'Samhæft',
    et: 'Ühilduv',
    lv: 'Saderīgs',
    lt: 'Suderinama',
    ga: 'Comhoiriúnach',
    mt: 'Kompatibbli',
    be: 'Сумяшчальна',
    lb: 'Kompatibel',
    ca: 'Compatible',
    cnr: 'Kompatibilno',
    hy: 'Համատեղելի',
    ka: 'თავსებადი',
    az: 'Uyğundur',
  );

  String get protocolIncompatibleText => choose(
    vi: 'Không tương thích',
    en: 'Incompatible',
    zh: '不兼容',
    ko: '호환되지 않음',
    ja: '互換性なし',
    de: 'Nicht kompatibel',
    ru: 'Несовместимо',
    fr: 'Incompatible',
    es: 'Incompatible',
    id: 'Tidak kompatibel',
    th: 'ไม่เข้ากัน',
    ms: 'Tidak serasi',
    fil: 'Hindi compatible',
    km: 'មិនឆបគ្នា',
    my: 'မကိုက်ညီပါ',
    lo: 'ບໍ່ເຂົ້າກັນ',
    ta: 'இணக்கமற்றது',
    pt: 'Incompatível',
    tet: 'La kompatível',
    it: 'Non compatibile',
    pl: 'Niezgodny',
    nl: 'Niet compatibel',
    cs: 'Nekompatibilní',
    sk: 'Nekompatibilné',
    uk: 'Несумісно',
    ro: 'Incompatibil',
    hu: 'Nem kompatibilis',
    bg: 'Несъвместимо',
    hr: 'Nije kompatibilno',
    sr: 'Nije kompatibilno',
    bs: 'Nije kompatibilno',
    sl: 'Ni združljivo',
    mk: 'Некомпатибилно',
    sq: 'I papërputhshëm',
    el: 'Μη συμβατό',
    tr: 'Uyumsuz',
    sv: 'Inte kompatibel',
    da: 'Ikke kompatibel',
    nb: 'Ikke kompatibel',
    fi: 'Ei yhteensopiva',
    isLang: 'Ósamhæft',
    et: 'Ei ühildu',
    lv: 'Nav saderīgs',
    lt: 'Nesuderinama',
    ga: 'Neamh-chomhoiriúnach',
    mt: 'Mhux kompatibbli',
    be: 'Несумяшчальна',
    lb: 'Net kompatibel',
    ca: 'No compatible',
    cnr: 'Nije kompatibilno',
    hy: 'Անհամատեղելի',
    ka: 'შეუთავსებელი',
    az: 'Uyğun deyil',
  );
}
