part of 'app_strings.dart';

extension VibrationAlertFeatureStrings on AppStrings {
  String get vibrationStrongAlertLevelTitle => choose(
    vi: "Mức kích hoạt cảnh báo mạnh",
    en: "Strong alert trigger level",
    zh: "强提醒触发级别",
    ko: "강한 경고 시작 단계",
    ja: "強い警告の開始レベル",
    de: "Auslösestufe für starke Warnung",
    ru: "Уровень запуска сильного оповещения",
    fr: "Niveau de déclenchement de l’alerte forte",
    es: "Nivel de activación de alerta fuerte",
    id: "Tingkat pemicu peringatan kuat",
    th: "ระดับเริ่มการแจ้งเตือนแบบแรง",
    ms: "Tahap pencetus amaran kuat",
    fil: "Antas ng pag-trigger ng malakas na alerto",
    km: "កម្រិតបើកការជូនដំណឹងខ្លាំង",
    my: "ပြင်းထန်သတိပေးချက် စတင်မည့်အဆင့်",
    lo: "ລະດັບເລີ່ມການເຕືອນແຮງ",
    ta: "வலுவான எச்சரிக்கை தொடங்கும் நிலை",
    pt: "Nível de ativação do alerta forte",
    tet: "Nivel atu ativa alerta forte",
    it: "Livello di attivazione dell’avviso forte",
    pl: "Poziom uruchomienia silnego alertu",
    nl: "Activeringsniveau voor sterke waarschuwing",
    cs: "Úroveň spuštění silného upozornění",
    sk: "Úroveň spustenia silného upozornenia",
    uk: "Рівень запуску сильного сповіщення",
    ro: "Nivel de declanșare a alertei puternice",
    hu: "Erős riasztás indítási szintje",
    bg: "Ниво за задействане на силно предупреждение",
    hr: "Razina pokretanja snažnog upozorenja",
    sr: "Nivo pokretanja snažnog upozorenja",
    bs: "Nivo pokretanja snažnog upozorenja",
    sl: "Raven sprožitve močnega opozorila",
    mk: "Ниво за активирање силно предупредување",
    sq: "Niveli i aktivizimit të alarmit të fortë",
    el: "Επίπεδο ενεργοποίησης ισχυρής ειδοποίησης",
    tr: "Güçlü uyarı tetikleme seviyesi",
    sv: "Utlösningsnivå för stark varning",
    da: "Udløsningsniveau for kraftig advarsel",
    nb: "Utløsningsnivå for sterk varsling",
    fi: "Vahvan hälytyksen käynnistystaso",
    isLang: "Kveikjustig sterkrar viðvörunar",
    et: "Tugeva hoiatuse käivitustase",
    lv: "Spēcīgā brīdinājuma aktivizēšanas līmenis",
    lt: "Stipraus įspėjimo suaktyvinimo lygis",
    ga: "Leibhéal spreagtha an rabhaidh láidir",
    mt: "Livell ta’ attivazzjoni tat-twissija qawwija",
    be: "Узровень запуску моцнага папярэджання",
    lb: "Ausléiseniveau fir staark Warnung",
    ca: "Nivell d’activació de l’avís fort",
    cnr: "Nivo pokretanja snažnog upozorenja",
    hy: "Ուժեղ ազդանշանի գործարկման մակարդակ",
    ka: "ძლიერი გაფრთხილების ჩართვის დონე",
    az: "Güclü xəbərdarlığın işə düşmə səviyyəsi",
  );

  String get vibrationStrongAlertLevelDescription => choose(
    vi: "Chọn mức rung để bật Fullscreen Alarm và còi điện thoại.",
    en: "Choose the vibration level that activates Fullscreen Alarm and the phone siren.",
    zh: "选择触发全屏警报和手机警报声的振动级别。",
    ko: "전체 화면 경고와 휴대전화 사이렌을 시작할 진동 단계를 선택하세요.",
    ja: "全画面アラームと端末のサイレンを開始する振動レベルを選択します。",
    de: "Wähle die Vibrationsstufe, ab der Vollbildalarm und Telefonsirene aktiviert werden.",
    ru: "Выберите уровень вибрации, при котором включаются полноэкранная тревога и сирена телефона.",
    fr: "Choisissez le niveau de vibration qui active l’alarme plein écran et la sirène du téléphone.",
    es: "Elige el nivel de vibración que activa la alarma a pantalla completa y la sirena del teléfono.",
    id: "Pilih tingkat getaran yang mengaktifkan alarm layar penuh dan sirene ponsel.",
    th: "เลือกระดับการสั่นที่จะเปิดการเตือนเต็มหน้าจอและเสียงไซเรนของโทรศัพท์",
    ms: "Pilih tahap getaran yang mengaktifkan penggera skrin penuh dan siren telefon.",
    fil:
        "Piliin ang antas ng vibration na magpapagana sa full-screen alarm at sirena ng telepono.",
    km: "ជ្រើសកម្រិតរំញ័រដែលនឹងបើកការជូនដំណឹងពេញអេក្រង់ និងស៊ីរ៉ែនទូរស័ព្ទ។",
    my: "မျက်နှာပြင်အပြည့် Alarm နှင့် ဖုန်း siren ကို စတင်မည့် တုန်ခါမှုအဆင့်ကို ရွေးပါ။",
    lo: "ເລືອກລະດັບການສັ່ນທີ່ຈະເປີດແຈ້ງເຕືອນເຕັມຈໍ ແລະ ສຽງໄຊເຣນໂທລະສັບ.",
    ta: "முழுத்திரை அலாரம் மற்றும் தொலைபேசி சைரனை இயக்கும் அதிர்வு நிலையைத் தேர்ந்தெடுக்கவும்.",
    pt: "Escolha o nível de vibração que ativa o alarme em ecrã inteiro e a sirene do telefone.",
    tet:
        "Hili nivel vibrasaun ne’ebé ativa alarme tela tomak no sirene telemóvel.",
    it: "Scegli il livello di vibrazione che attiva l’allarme a schermo intero e la sirena del telefono.",
    pl: "Wybierz poziom wibracji, który uruchamia alarm pełnoekranowy i syrenę telefonu.",
    nl: "Kies het trillingsniveau waarbij het schermvullende alarm en de telefoonsirene starten.",
    cs: "Vyberte úroveň vibrací, při které se spustí celoobrazovkový alarm a siréna telefonu.",
    sk: "Vyberte úroveň vibrácií, pri ktorej sa spustí celoobrazovkový alarm a siréna telefónu.",
    uk: "Виберіть рівень вібрації, за якого вмикаються повноекранна тривога та сирена телефона.",
    ro: "Alege nivelul de vibrație care activează alarma pe ecran complet și sirena telefonului.",
    hu: "Válaszd ki azt a rezgésszintet, amely bekapcsolja a teljes képernyős riasztást és a telefon szirénáját.",
    bg: "Изберете нивото на вибрация, което включва алармата на цял екран и сирената на телефона.",
    hr: "Odaberite razinu vibracije koja uključuje alarm preko cijelog zaslona i sirenu telefona.",
    sr: "Izaberite nivo vibracije koji uključuje alarm preko celog ekrana i sirenu telefona.",
    bs: "Odaberite nivo vibracije koji uključuje alarm preko cijelog ekrana i sirenu telefona.",
    sl: "Izberite raven vibracij, ki vklopi celozaslonski alarm in sireno telefona.",
    mk: "Изберете ниво на вибрација што го вклучува алармот на цел екран и сирената на телефонот.",
    sq: "Zgjidh nivelin e dridhjes që aktivizon alarmin në ekran të plotë dhe sirenën e telefonit.",
    el: "Επιλέξτε το επίπεδο δόνησης που ενεργοποιεί την ειδοποίηση πλήρους οθόνης και τη σειρήνα του τηλεφώνου.",
    tr: "Tam ekran alarmı ve telefon sirenini etkinleştirecek titreşim seviyesini seçin.",
    sv: "Välj vibrationsnivån som aktiverar helskärmslarm och telefonens siren.",
    da: "Vælg det vibrationsniveau, der aktiverer fuldskærmsalarm og telefonens sirene.",
    nb: "Velg vibrasjonsnivået som aktiverer fullskjermalarm og telefonsirene.",
    fi: "Valitse värinätaso, joka käynnistää koko näytön hälytyksen ja puhelimen sireenin.",
    isLang:
        "Veldu titringsstigið sem kveikir á viðvörun í fullum skjá og sírenu símans.",
    et: "Vali vibratsioonitase, mis käivitab täisekraani häire ja telefoni sireeni.",
    lv: "Izvēlieties vibrācijas līmeni, kas ieslēdz pilnekrāna trauksmi un tālruņa sirēnu.",
    lt: "Pasirinkite vibracijos lygį, kuris įjungia viso ekrano signalą ir telefono sireną.",
    ga: "Roghnaigh an leibhéal creatha a chuireann an t-aláram lánscáileáin agus siren an fhóin ar siúl.",
    mt: "Agħżel il-livell ta’ vibrazzjoni li jattiva l-allarm fuq skrin sħiħ u s-sirena tat-telefon.",
    be: "Выберыце ўзровень вібрацыі, пры якім уключаюцца поўнаэкранная трывога і сірэна тэлефона.",
    lb: "Wielt de Vibratiounsniveau, deen de Vollbildalarm an d’Telefonsirène aktivéiert.",
    ca: "Tria el nivell de vibració que activa l’alarma a pantalla completa i la sirena del telèfon.",
    cnr:
        "Izaberite nivo vibracije koji uključuje alarm preko cijelog ekrana i sirenu telefona.",
    hy: "Ընտրեք թրթռման մակարդակը, որը միացնում է ամբողջ էկրանով ահազանգը և հեռախոսի շչակը։",
    ka: "აირჩიეთ ვიბრაციის დონე, რომელიც ჩართავს სრულეკრანიან განგაშსა და ტელეფონის სირენას.",
    az: "Tam ekran siqnalını və telefon sirenini aktivləşdirən vibrasiya səviyyəsini seçin.",
  );

  String get vibrationWarningStrongAlertDescription => choose(
    vi: "Nhạy hơn: cảnh báo mạnh ngay khi rung đạt mức Cần chú ý.",
    en: "More sensitive: strong alert starts as soon as vibration reaches Needs attention.",
    zh: "更灵敏：振动达到“需要注意”时立即启动强提醒。",
    ko: "더 민감하게: 진동이 확인 필요 단계에 도달하면 즉시 강한 경고를 시작합니다.",
    ja: "高感度：振動が「要注意」に達した時点で強い警告を開始します。",
    de: "Empfindlicher: Die starke Warnung startet bereits bei „Aufmerksamkeit erforderlich“.",
    ru: "Более чувствительно: сильное оповещение включается уже на уровне «Требует внимания».",
    fr: "Plus sensible : l’alerte forte démarre dès le niveau « Attention requise ».",
    es: "Más sensible: la alerta fuerte se activa al llegar a «Requiere atención».",
    id: "Lebih sensitif: peringatan kuat dimulai saat getaran mencapai Perlu diperhatikan.",
    th: "ไวขึ้น: เริ่มการแจ้งเตือนแบบแรงทันทีเมื่อการสั่นถึงระดับต้องตรวจสอบ",
    ms: "Lebih sensitif: amaran kuat bermula apabila getaran mencapai Perlu perhatian.",
    fil:
        "Mas sensitibo: magsisimula ang malakas na alerto kapag umabot sa Kailangang bigyang-pansin.",
    km: "រសើបជាង៖ ការជូនដំណឹងខ្លាំងចាប់ផ្តើមភ្លាមៗនៅកម្រិតត្រូវការការយកចិត្តទុកដាក់។",
    my: "ပိုမိုအာရုံခံ៖ တုန်ခါမှုက သတိပြုရန်လိုသည့်အဆင့်ရောက်သည်နှင့် ပြင်းထန်သတိပေးချက် စတင်မည်။",
    lo: "ໄວກວ່າ: ເລີ່ມການເຕືອນແຮງເມື່ອການສັ່ນຮອດລະດັບຕ້ອງໃສ່ໃຈ.",
    ta: "அதிக உணர்திறன்: அதிர்வு கவனம் தேவை நிலையை அடைந்தவுடன் வலுவான எச்சரிக்கை தொடங்கும்.",
    pt: "Mais sensível: o alerta forte começa assim que a vibração atinge Precisa de atenção.",
    tet:
        "Sensível liu: alerta forte hahú bainhira vibrasaun to’o nivel Presiza atensaun.",
    it: "Più sensibile: l’avviso forte parte appena la vibrazione raggiunge Da controllare.",
    pl: "Większa czułość: silny alert zaczyna się już przy poziomie Wymaga uwagi.",
    nl: "Gevoeliger: de sterke waarschuwing start zodra Aandacht vereist wordt bereikt.",
    cs: "Citlivější: silné upozornění se spustí už při úrovni Vyžaduje pozornost.",
    sk: "Citlivejšie: silné upozornenie sa spustí už pri úrovni Vyžaduje pozornosť.",
    uk: "Чутливіше: сильне сповіщення запускається вже на рівні Потребує уваги.",
    ro: "Mai sensibil: alerta puternică pornește când vibrația ajunge la Necesită atenție.",
    hu: "Érzékenyebb: az erős riasztás már a Figyelmet igényel szintnél elindul.",
    bg: "По-чувствително: силното предупреждение започва още при Изисква внимание.",
    hr: "Osjetljivije: snažno upozorenje počinje čim vibracija dosegne Zahtijeva pozornost.",
    sr: "Osetljivije: snažno upozorenje počinje čim vibracija dostigne Zahteva pažnju.",
    bs: "Osjetljivije: snažno upozorenje počinje čim vibracija dostigne Zahtijeva pozornost.",
    sl: "Bolj občutljivo: močno opozorilo se začne že pri ravni Zahteva pozornost.",
    mk: "Почувствително: силното предупредување почнува кога вибрацијата ќе достигне Потребно внимание.",
    sq: "Më i ndjeshëm: alarmi i fortë nis sapo dridhja arrin Kërkon vëmendje.",
    el: "Πιο ευαίσθητο: η ισχυρή ειδοποίηση ξεκινά μόλις η δόνηση φτάσει στο Χρειάζεται προσοχή.",
    tr: "Daha hassas: titreşim Dikkat gerektiriyor seviyesine ulaşınca güçlü uyarı başlar.",
    sv: "Känsligare: stark varning startar redan vid Kräver uppmärksamhet.",
    da: "Mere følsom: kraftig advarsel starter allerede ved Kræver opmærksomhed.",
    nb: "Mer følsom: sterk varsling starter allerede ved Krever oppmerksomhet.",
    fi: "Herkempi: vahva hälytys alkaa jo Vaatii huomiota -tasolla.",
    isLang:
        "Næmara: sterk viðvörun hefst um leið og titringur nær Þarf athygli.",
    et: "Tundlikum: tugev hoiatus käivitub juba tasemel Vajab tähelepanu.",
    lv: "Jutīgāks: spēcīgais brīdinājums sākas jau līmenī Nepieciešama uzmanība.",
    lt: "Jautriau: stiprus įspėjimas prasideda jau lygiu Reikia dėmesio.",
    ga: "Níos íogaire: tosaíonn an rabhadh láidir chomh luath agus a shroicheann an creathadh Teastaíonn aird.",
    mt: "Aktar sensittiv: it-twissija qawwija tibda hekk kif il-vibrazzjoni tilħaq Jeħtieġ attenzjoni.",
    be: "Больш адчувальна: моцнае папярэджанне запускаецца ўжо на ўзроўні Патрабуе ўвагі.",
    lb: "Méi sensibel: déi staark Warnung start schonn bei Opmierksamkeet néideg.",
    ca: "Més sensible: l’avís fort comença quan la vibració arriba a Requereix atenció.",
    cnr:
        "Osjetljivije: snažno upozorenje počinje čim vibracija dostigne Zahtijeva pažnju.",
    hy: "Ավելի զգայուն․ ուժեղ ազդանշանը սկսվում է հենց թրթռումը հասնում է «Ուշադրություն է պահանջում» մակարդակին։",
    ka: "უფრო მგრძნობიარე: ძლიერი გაფრთხილება იწყება, როგორც კი ვიბრაცია მიაღწევს ყურადღებას საჭიროებს დონეს.",
    az: "Daha həssas: vibrasiya Diqqət tələb edir səviyyəsinə çatan kimi güclü xəbərdarlıq başlayır.",
  );

  String get vibrationAlarmStrongAlertDescription => choose(
    vi: "Ít báo nhầm hơn: chỉ cảnh báo mạnh khi rung đạt mức Báo động.",
    en: "Fewer false alarms: strong alert starts only when vibration reaches Alarm.",
    zh: "减少误报：仅当振动达到“警报”级别时启动强提醒。",
    ko: "오경보 감소: 진동이 경보 단계에 도달했을 때만 강한 경고를 시작합니다.",
    ja: "誤報を低減：振動が「アラーム」に達した場合のみ強い警告を開始します。",
    de: "Weniger Fehlalarme: Die starke Warnung startet erst bei „Alarm“.",
    ru: "Меньше ложных тревог: сильное оповещение включается только на уровне «Тревога».",
    fr: "Moins de fausses alertes : l’alerte forte démarre uniquement au niveau « Alarme ».",
    es: "Menos falsas alarmas: la alerta fuerte se activa solo al llegar a «Alarma».",
    id: "Lebih sedikit alarm palsu: peringatan kuat hanya dimulai saat getaran mencapai Alarm.",
    th: "ลดการแจ้งเตือนผิดพลาด: เริ่มการแจ้งเตือนแบบแรงเมื่อการสั่นถึงระดับสัญญาณเตือนเท่านั้น",
    ms: "Kurang amaran palsu: amaran kuat hanya bermula apabila getaran mencapai Penggera.",
    fil:
        "Mas kaunting maling alerto: magsisimula lamang ang malakas na alerto kapag umabot sa Alarm.",
    km: "កាត់បន្ថយការជូនដំណឹងខុស៖ ការជូនដំណឹងខ្លាំងចាប់ផ្តើមតែនៅកម្រិត Alarm។",
    my: "မှားယွင်းသတိပေးချက်နည်းရန်：တုန်ခါမှုက Alarm အဆင့်ရောက်မှသာ ပြင်းထန်သတိပေးချက် စတင်မည်။",
    lo: "ຫຼຸດການເຕືອນຜິດ: ເລີ່ມການເຕືອນແຮງສະເພາະເມື່ອຮອດລະດັບ Alarm.",
    ta: "தவறான எச்சரிக்கைகள் குறைவு: அதிர்வு அலாரம் நிலையை அடைந்தால் மட்டுமே வலுவான எச்சரிக்கை தொடங்கும்.",
    pt: "Menos falsos alarmes: o alerta forte começa apenas quando a vibração atinge Alarme.",
    tet:
        "Redús alerta falsu: alerta forte hahú deit bainhira vibrasaun to’o nivel Alarme.",
    it: "Meno falsi allarmi: l’avviso forte parte solo quando la vibrazione raggiunge Allarme.",
    pl: "Mniej fałszywych alarmów: silny alert zaczyna się dopiero przy poziomie Alarm.",
    nl: "Minder valse alarmen: de sterke waarschuwing start pas bij Alarm.",
    cs: "Méně falešných poplachů: silné upozornění se spustí až při úrovni Alarm.",
    sk: "Menej falošných poplachov: silné upozornenie sa spustí až pri úrovni Alarm.",
    uk: "Менше хибних тривог: сильне сповіщення запускається лише на рівні Тривога.",
    ro: "Mai puține alarme false: alerta puternică pornește doar când vibrația ajunge la Alarmă.",
    hu: "Kevesebb téves riasztás: az erős riasztás csak a Riasztás szintnél indul el.",
    bg: "По-малко фалшиви тревоги: силното предупреждение започва само при Аларма.",
    hr: "Manje lažnih alarma: snažno upozorenje počinje tek na razini Alarm.",
    sr: "Manje lažnih alarma: snažno upozorenje počinje tek na nivou Alarm.",
    bs: "Manje lažnih alarma: snažno upozorenje počinje tek na nivou Alarm.",
    sl: "Manj lažnih alarmov: močno opozorilo se začne šele pri ravni Alarm.",
    mk: "Помалку лажни аларми: силното предупредување почнува само на ниво Аларм.",
    sq: "Më pak alarme të rreme: alarmi i fortë nis vetëm kur dridhja arrin Alarm.",
    el: "Λιγότεροι ψευδείς συναγερμοί: η ισχυρή ειδοποίηση ξεκινά μόνο στο επίπεδο Συναγερμός.",
    tr: "Daha az yanlış alarm: güçlü uyarı yalnızca Alarm seviyesinde başlar.",
    sv: "Färre falsklarm: stark varning startar först vid Alarm.",
    da: "Færre falske alarmer: kraftig advarsel starter først ved Alarm.",
    nb: "Færre falske alarmer: sterk varsling starter først ved Alarm.",
    fi: "Vähemmän vääriä hälytyksiä: vahva hälytys alkaa vasta Hälytys-tasolla.",
    isLang: "Færri falsviðvaranir: sterk viðvörun hefst aðeins við Viðvörun.",
    et: "Vähem valehäireid: tugev hoiatus käivitub alles tasemel Häire.",
    lv: "Mazāk viltus trauksmju: spēcīgais brīdinājums sākas tikai līmenī Trauksme.",
    lt: "Mažiau klaidingų signalų: stiprus įspėjimas prasideda tik lygiu Signalas.",
    ga: "Níos lú foláireamh bréagach: ní thosaíonn an rabhadh láidir ach ag leibhéal Aláram.",
    mt: "Inqas allarmi foloz: it-twissija qawwija tibda biss fil-livell Allarm.",
    be: "Менш ілжывых трывог: моцнае папярэджанне запускаецца толькі на ўзроўні Трывога.",
    lb: "Manner falsch Alarm: déi staark Warnung start eréischt bei Alarm.",
    ca: "Menys falses alarmes: l’avís fort comença només quan la vibració arriba a Alarma.",
    cnr: "Manje lažnih alarma: snažno upozorenje počinje tek na nivou Alarm.",
    hy: "Ավելի քիչ կեղծ ահազանգեր․ ուժեղ ազդանշանը սկսվում է միայն «Ահազանգ» մակարդակում։",
    ka: "ნაკლები ცრუ განგაში: ძლიერი გაფრთხილება იწყება მხოლოდ განგაშის დონეზე.",
    az: "Daha az yalnış siqnal: güclü xəbərdarlıq yalnız Siqnal səviyyəsində başlayır.",
  );
}
