// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADmOH14fgdQH97ze3cuYCwG_1zbYGqOUo',
    appId: '1:83888615408:web:079b32e130478242bd7735',
    messagingSenderId: '83888615408',
    projectId: 'safehome-10cc9',
    authDomain: 'safehome-10cc9.firebaseapp.com',
    databaseURL:
        'https://safehome-10cc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safehome-10cc9.firebasestorage.app',
    measurementId: 'G-JKFWRB2C6N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0-C9tL3V0Kp8HD7v7nOPIELeTvNz_QK8',
    appId: '1:83888615408:ios:dba94b7072bb3efdbd7735',
    messagingSenderId: '83888615408',
    projectId: 'safehome-10cc9',
    databaseURL:
        'https://safehome-10cc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safehome-10cc9.firebasestorage.app',
    iosBundleId: 'com.myfamily.maiyen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0-C9tL3V0Kp8HD7v7nOPIELeTvNz_QK8',
    appId: '1:83888615408:ios:ce97c5ecf96b13bdbd7735',
    messagingSenderId: '83888615408',
    projectId: 'safehome-10cc9',
    databaseURL:
        'https://safehome-10cc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safehome-10cc9.firebasestorage.app',
    iosBundleId: 'com.myfamily.maiyen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADmOH14fgdQH97ze3cuYCwG_1zbYGqOUo',
    appId: '1:83888615408:web:21a4d158a12993efbd7735',
    messagingSenderId: '83888615408',
    projectId: 'safehome-10cc9',
    authDomain: 'safehome-10cc9.firebaseapp.com',
    databaseURL:
        'https://safehome-10cc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safehome-10cc9.firebasestorage.app',
    measurementId: 'G-MCN3XK7MGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEYXZZz9AJA1N8ulrGLa-6u-nB1-opWv4',
    appId: '1:83888615408:android:2185565eaf57dcd9bd7735',
    messagingSenderId: '83888615408',
    projectId: 'safehome-10cc9',
    databaseURL:
        'https://safehome-10cc9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safehome-10cc9.firebasestorage.app',
  );
}
